(function(g){var window=this;'use strict';var E2=function(a){a.publish("cardstatechange",a.El()&&a.Up()?1:0)},F2=function(a,b){var c=g.Ra(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},Qdb=function(a){var b=g.Bm(a);
a=g.Em(a);return new g.pm(b.x,b.y,a.width,a.height)},Rdb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.Bs(a,b,function(){g.Cs(e);c.apply(a,arguments)},d)},I2=function(a){a=g.Va(a);
delete G2[a];g.Ig(G2)&&H2&&H2.stop()},Tdb=function(){H2||(H2=new g.ep(function(){Sdb()},20));
var a=H2;a.isActive()||a.start()},Sdb=function(){var a=g.Ya();
g.yg(G2,function(b){Udb(b,a)});
g.Ig(G2)||Tdb()},J2=function(a,b,c,d){g.rp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Udb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Vdb(a,a.progress);a.progress==1?(a.j=0,I2(a),a.onFinish(),a.Is()):a.isPlaying()&&a.rO()},Vdb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Wdb=function(a,b){g.Mh.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},K2=function(a,b,c,d,e){J2.call(this,b,c,d,e);
this.element=a},Xdb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
K2.call(this,a,b,c,d,e)},Ydb=function(a){return Math.pow(a,3)},Zdb=function(a){return 3*a*a-2*a*a*a},$db=function(a){g.O.call(this);
this.B=a||window;this.j=[]},L2=function(a){return a.baseUrl||null},M2=function(a,b){return g.on(g.Cl(a,b),function(c){return!!c})},aeb=function(a,b,c){function d(oa){var Y=oa.hovercardButton;
if(!Y)return null;Y=Y.subscribeButtonRenderer;if(!Y)return null;var R=f(Y.unsubscribedButtonText),T=f(Y.subscribedButtonText);if(Y.subscribed){var v=f(Y.subscriberCountWithUnsubscribeText);var W=f(Y.subscriberCountText)}else v=f(Y.subscriberCountText),W=f(Y.subscriberCountWithSubscribeText);var bb=null;if(oa.signinEndpoint){bb=F2(oa,"signinEndpoint","webNavigationEndpointData","url");if(!bb){var ub,ob;bb=(ob=g.Q((ub=Y.signInEndpoint)==null?void 0:ub.commandMetadata,g.x1))==null?void 0:ob.url}if(!bb)return null}return R&&
(T||bb)?{subscribed:Y.subscribed,subscribeText:R,subscribeCount:v,unsubscribeText:T,unsubscribeCount:W,enabled:Y.enabled,signinUrl:bb,classic:oa.useClassicSubscribeButton}:null}
function e(oa){if(oa){var Y=[],R=oa.videoId;R&&Y.push("v="+R);(R=oa.playlistId)&&Y.push("list="+R);(oa=oa.startTimeSeconds)&&Y.push("t="+oa);return"/watch?"+Y.join("&")}}
function f(oa){if(!oa)return null;var Y=oa.simpleText;return Y?Y:oa.runs?g.Cl(oa.runs,function(R){return R.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,y=!1,A=null,C=null,G=null,H=null,M=null,N=null;if(h==="VIDEO")g.Q(l,g.Vx)?m=g.Q(l,g.Vx).url:(N=g.Q(l,g.OQ),m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.Q(l,g.Vx)?m=g.Q(l,g.Vx).url:(N=g.Q(l,g.OQ),m=e(N)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(y=F2(l,"browseEndpoint","browseId"))u=y,m="/channel/"+u;n=!1;q="new";(y=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((G=F2(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=F2(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=F2(b,"title","accessibility","accessibilityData","label");var X=b.endpoint?b.endpoint.clickTrackingParams:
null,V="";if(b.metadata){var ea=f(b.metadata);ea&&(V=ea)}return{id:"element-"+c,type:h,title:f(b.title),metadata:V,callToAction:f(b.callToAction),nY:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,pG:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:y,targetUrl:m||null,H$:n,sessionData:X?{itct:X}:null,mfa:q,EE:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:M2(b.impressionUrls||[],L2),x$:M2(b.hovercardShowUrls||[],L2),clickUrls:M2(l.loggingUrls||[],L2),visualElement:g.Fw(b.trackingParams),productPrice:H,additionalFeesText:M,watchEndpoint:N||null}},beb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:M2(a.impressionUrls||[],L2),elements:M2(a.elements||[],function(d,e){return aeb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Fw(a.trackingParams));return c},ceb=function(a){g.VX.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.W=!0;this.K=0;a=a.U();this.Z=g.nP(a)||g.pP(a);this.events=new g.NF(this);g.P(this,this.events);this.events.T(this.player,g.pE("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.qE("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.jc);this.events.T(window,"focus",this.nda);this.load();var b=g.dh("STYLE");(g.Sg("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.ih(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},deb=function(a){return a.player.getVideoData().Jf?"current":a.Z?"new":"current"},N2=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},eeb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=beb(f,deb(a))));O2(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Jw;d&&(c.postParams={ad_tracking:d});if(b=g.WLa(b))if(b=g.Jf(b),b=g.Ff(b))a.C=g.Er(b,c)},O2=function(a,b,c){c=c===void 0?!0:c;
a.player.jf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.w(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.N.length>0&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&feb(a);c=[];d=new g.nE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.S({I:"div",S:"ytp-ce-shadow"}),g.iS(a.player,a.B.element,4),a.D=new g.my(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=geb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.iS(a.player,f.element,4);var h=new g.nE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);heb(a,f,e)}else g.Rw(new g.Zs("buildEndscreenElement null",
e))}a.player.nf(c);a.jc()}},feb=function(a){var b=g.Hw(),c=g.Iw();
c&&b&&a.endscreen.visualElement&&g.dr(g.cx)(void 0,c,b,a.endscreen.visualElement)},geb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.EE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:P2(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:Q2(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.vp(b.title||"")},va:b.title},{I:"div",S:b.pG?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
va:b.videoDuration||void 0}]}]};c=new g.S(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.EE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:P2(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:Q2(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.vp(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.S(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.EE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],X:{href:Q2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.vp(b.title||"")},va:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:P2(b)}]};c=new g.S(c);var d=g.Wg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.mp(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.BY(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.EE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.vp(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-website-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],X:{href:Q2(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:P2(b)},{I:"div",S:"ytp-ce-expanding-icon",X:ieb(b.iconUrl)}]};c=new g.S(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.EE||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.vp(b.title||"")},va:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:Q2(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:P2(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
va:b.callToAction||void 0}]}]},c=new g.S(a)}b.isPlaceholder&&g.mp(c.element,"ytp-ce-placeholder");return c},P2=function(a){if(a.nY)var b=a.nY.thumbnails;
return ieb(b?b[b.length-1].url:null)},ieb=function(a){return a?{style:"background-image: url("+a+")"}:{}},heb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.W&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.mp(b.element,"ytp-ce-force-expand"),R2(a,c.id,!0)):(g.op(b.element,"ytp-ce-force-expand"),g.op(b.element,"ytp-ce-element-hover"),R2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){jeb(a,b,c)});
b.listen("mouseleave",function(){keb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.mp(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){leb(a,c,m)});
b.listen("keypress",function(m){leb(a,c,m)});
b.listen("focus",function(){jeb(a,b,c)});
b.listen("blur",function(){keb(a,b,c)});
b.listen("touchstart",function(){jeb(a,b,c)});
var l=g.Yg("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.op(b.element,"ytp-ce-element-hover");g.op(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.W=m.keyCode===9&&!m.shiftKey});
d(g.Yg("ytp-sb-subscribe",b.element));d(g.Yg("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},leb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.lp(d,"ytp-ce-element");){g.lp(d,"subscribe-label")&&meb(a,b);
if(g.lp(d,"ytp-ce-channel-subscribe"))return;d=d.parentElement||null}if(!d||g.lp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])keb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.mfa==="new")meb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Jf(Q2(a,b.targetUrl)),c=g.Ff(c),g.bz(c,void 0,b.sessionData);else{var e=g.CP(a.player.U())||a.player.getVideoData().Jf,f=function(){var h=Q2(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=
g.jr(h);e&&n&&(n.v||n.list)?a.player.Fp(n.v,l,n.list,!1,void 0,m||void 0):g.az(h,l)};
meb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},Q2=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.KP(a)+b}else return"";return b},jeb=function(a,b,c){g.lp(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.mp(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.ep(function(){g.mp(b.element,"ytp-ce-element-hover")},200)).start():g.mp(b.element,"ytp-ce-element-hover"),S2(a,c.x$),R2(a,c.id,!0))},keb=function(a,b,c){g.op(b.element,"ytp-ce-element-hover");
g.op(b.element,"ytp-ce-force-expand");R2(a,c.id,!1)},R2=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.w(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.qp(a.j[e].element,"ytp-ce-element-shadow-show",c)},S2=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||N2(a))c&&c();else{b=neb(a,b);var e=0,f=!1,h=new g.ep(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.$u(b[a],d)}},meb=function(a,b,c){S2(a,b.clickUrls,c);
(a=g.Iw())&&b.H$&&g.nx(a,b.visualElement)},neb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(oeb(b[d],c));return a},oeb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},peb=function(a){return typeof a==="string"?a:""},T2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},qeb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},U2=function(a){return a.value?a.value:null},V2=function(a){if(!a)return null;
var b=g.Jf(peb(a.value));b=g.Ff(b);if(!b)return null;var c=T2(a.target,reb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new qeb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},seb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},veb=function(a){if(!a)return null;
var b=T2(a.type,teb),c=T2(a.trigger,ueb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=V2(a?a:null);return b?new seb(b,c,a):null},web=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},xeb=function(a,b){return g.Tb(a.action,b)},yeb=function(a,b){this.context=a;
this.j=b},zeb=function(a){return a.customMessage?W2("div","iv-card-message",a.customMessage):""},X2=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},Aeb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.w(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(W2("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},W2=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.vp(c);return{I:a,X:b,va:c}},Beb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.SE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.SE+");");c.dir=g.vp(a.customMessage);var d=[{I:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,X:c,V:d}},Y2=function(a,b,c,d){if(d){b=g.w(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.uj.click,5)}},Ceb=function(a,b){this.merchant=a;
this.price=b},Deb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},Eeb=function(a,b){return b?b:Deb(a)?"current":"new"},Z2=function(a,b){g.O.call(this);
var c=this;this.element=a;this.context=b;this.kb=!1;this.Ta=new Map;this.Wa=new Map;this.context.J.addEventListener(g.pE("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.qE("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)})},$2=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.LN(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.kb=!1});
a.context.j.listen(b,"touchmove",function(){a.kb=!0})},Feb=function(a){var b;
return((b=g.Q(a,g.Vx))==null?0:b.url)?g.Q(a,g.Vx).url:(a=g.Q(a,g.OQ))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},a3=function(a,b,c){return{NZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
l3:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
mN:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Geb=function(a,b,c){Z2.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ab=this.La=this.Gb=this.C=this.isInitialized=!1;this.cards=[];this.rb=this.Z=this.Ja=this.G=this.Ua=this.j=null;this.oa=[];this.qa=this.N=this.Gf=this.Fa=null;this.K=0;this.Ca=new g.ep(function(){},c.Y.hk?4E3:3E3);
g.P(this,this.Ca);this.ib=new g.ep(function(){});
g.P(this,this.ib);this.Aa=new yeb(c,function(e,f,h,l,m,n){$2(d,e,f,h,l,m,n)});
this.W=new g.S({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.P(this,this.W);this.D=this.W.element;this.Va=new g.my(this.W,330);g.P(this,this.Va);this.Lb=g.Yg("iv-drawer-header-text",this.D);this.B=g.Yg("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Gb&&b3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Gb=d.C)&&c3(d)});
this.Na=new g.NF(this);g.P(this,this.Na);this.J.addEventListener("videodatachange",this.xu.bind(this))},Heb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){b3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){c3(a)});
var c=b.headerText;g.kh(a.Lb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.Fw(b.trackingParams);a.N=g.Fw(b.closeTrackingParams);a.Gf=g.Fw(b.iconTrackingParams)},Ieb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.bb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.Bx(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,uj:{},Xp:null,fk:e.trackingParams?g.Fw(e.trackingParams):null,Gf:f&&f.trackingParams?g.Fw(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
SE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};d3(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.Bx(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:e3(a,c,b,f),sponsored:!1,uj:a3(f,e,f.command),Xp:f.trackingParams?g.Fw(f.trackingParams):null,fk:e.trackingParams?g.Fw(e.trackingParams):null,Gf:l&&l.trackingParams?g.Fw(l.trackingParams):null,imageUrl:f3(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.Bx(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,SE:null,title:f.title?g.Bx(f.title):"",customMessage:f.callToAction?g.Bx(f.callToAction):"",url:g.Q(f.command,g.Vx).url?V2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(f.command,g.Vx).url}):null,onClickCommand:null};d3(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.Bx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:e3(a,c,b,e),sponsored:!1,uj:a3(e,f,e.endpoint),Xp:e.trackingParams?g.Fw(e.trackingParams):null,fk:f.trackingParams?g.Fw(f.trackingParams):null,Gf:l&&l.trackingParams?g.Fw(l.trackingParams):null,channelId:g.Q(e.endpoint,g.hR).browseId,customMessage:e.customText?g.Bx(e.customText):null,profileImageUrl:f3(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.Bx(e.channelName):"",metaInfo:[e.subscriberCountText?g.Bx(e.subscriberCountText):""],url:V2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(e.endpoint,g.hR).canonicalBaseUrl?g.Q(e.endpoint,g.hR).canonicalBaseUrl:"/channel/"+g.Q(e.endpoint,g.hR).browseId}),onClickCommand:null};d3(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.Bx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:e3(a,c,b,e),sponsored:!1,uj:a3(e,f,e.action),Xp:e.trackingParams?g.Fw(e.trackingParams):null,fk:f.trackingParams?g.Fw(f.trackingParams):null,Gf:l&&l.trackingParams?g.Fw(l.trackingParams):null,wI:f3(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.Bx(e.customMessage):null,playlistVideoCount:g.Bx(e.playlistVideoCount),title:e.playlistTitle?g.Bx(e.playlistTitle):"",metaInfo:[e.channelName?g.Bx(e.channelName):
"",e.videoCountText?g.Bx(e.videoCountText):""],url:V2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Feb(e.action)}),onClickCommand:null};d3(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.Bx(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:e3(a,c,b,e),sponsored:!1,uj:a3(e,f,e.action),Xp:e.trackingParams?g.Fw(e.trackingParams):null,fk:f.trackingParams?g.Fw(f.trackingParams):null,Gf:l&&l.trackingParams?g.Fw(l.trackingParams):null,wI:f3(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.Bx(e.lengthString):null,customMessage:e.customMessage?g.Bx(e.customMessage):null,title:e.videoTitle?g.Bx(e.videoTitle):"",metaInfo:[e.channelName?g.Bx(e.channelName):
"",e.viewCountText?g.Bx(e.viewCountText):""],isLiveNow:!!e.badge,url:V2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Feb(e.action)}),onClickCommand:null};d3(a,b)}}}}}a.K++},f3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},e3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Keb=function(a,b){if(b=Jeb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Af.id),g.ih(b.YO),g.Xb(a.cards,b),a.BJ(),g3(a)},b3=function(a,b,c){if(!a.C){a.Va.show();
a.Ua=new g.ep(function(){g.mp(a.context.J.getRootNode(),g.G_.IV_DRAWER_OPEN)},0);
a.Ua.start();a.Na.T(a.B,"mousewheel",function(h){a.Ca.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.Iw();d&&a.Fa&&a.N&&g.lx(d,[a.Fa,a.N]);b={TRIGGER_TYPE:b};for(var e=g.w(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.P_||(f.P_=!0,Leb(a.context.logger,f.Af.uj.NZ,b)),d&&g.lx(d,[f.Af.Xp]);E2(a.J);c&&(a.G=new g.ep(function(){a.Ja=a.Z;a.rb.focus()},330),a.G.start())}},c3=function(a){a.C&&(a.Va.hide(),g.Is(a.Na),g.op(a.context.J.getRootNode(),g.G_.IV_DRAWER_OPEN),a.C=!1,E2(a.J),a.G&&a.G.stop(),a.G=new g.ep(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.G.start())},Meb=function(a){g.np(a.Ib(),
[g.G_.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.iS(a.J,a.D,5);a.nJ();a.Z=g.Yg("ytp-cards-button",a.J.getRootNode());a.rb=g.Yg("iv-drawer-close-button",a.D);a.isInitialized=!0},Neb=function(a){a.oa.push(g.rv("iv-teaser-shown",a.a5,a));
a.oa.push(g.rv("iv-teaser-hidden",a.daa,a));a.oa.push(g.rv("iv-teaser-clicked",a.Z4,a));a.Ab=!0},Oeb=function(a,b){var c;
return b.onClickCommand&&((c=g.Q(b.onClickCommand,g.Cbb))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.qa=b,!0):!1},Peb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.fQ(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.Q(h[0],g.w3a))==null?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},d3=function(a,b){if(!Oeb(a,b)||Peb(a,b)){var c=Qeb(a,b);
if(c){var d={Af:b,YO:c.element,P_:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Ab||Neb(a),Keb(a,b.id),c=a.findLastIndex(d),g.cc(a.cards,c,0,d));else{a.isInitialized||Meb(a);Keb(a,b.id);var e=a.findLastIndex(d);g.cc(a.cards,e,0,d);c.Ha(a.B,e);a.BJ()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,g3(a),Reb(a,d),b3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&Seb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){Seb(a,d)}),g3(a))}}},Qeb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",va:b.displayDomain}:void 0;var d=Beb(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?U2(b.url)||"":""},V:[X2(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[W2("h2",void 0,b.title),d]}]}]};c=new g.S(c);Y2(a,g.Xg("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],X:{href:U2(b.url)||"","data-ytid":b.channelId},V:[X2(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[zeb(b),{I:"h2",S:"iv-card-primary-link",va:b.title},Aeb(b)]}]}]};c=new g.S(c);Y2(a,g.Xg("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:U2(b.url)||""},V:[X2(b.wI,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[zeb(b),W2("h2","iv-card-primary-link",b.title),Aeb(b)]}]}]};
c=new g.S(c);Y2(a,g.Xg("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=b.offers.length!=0;c=["iv-card"];d="";var f=Beb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",va:f.merchant}),f={I:"div",V:e});e=b.url?U2(b.url)||"":"";c={I:"div",Ka:c,X:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",va:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[W2("h2",d,b.title),f]}]}]};c=new g.S(c);d=g.dh("span");g.kh(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Cd(d,"adInfo");Y2(a,g.Xg("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",va:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:((c=b.url)==null?void 0:U2(c))||""},V:[X2(b.wI,d),{I:"div",S:"iv-card-content",V:[zeb(b),W2("h2","iv-card-primary-link",b.title),Aeb(b),f]}]}]};c=new g.S(e);Y2(a,g.Xg("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Teb=function(a){if(a.j)return a.j.Af.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.Dl(a.cards,function(c){return c.Af.type==="productListing"})}return g.Dl(a.cards,function(c){return c.Af.type==="productListing"})},g3=function(a){g.qp(a.J.getRootNode(),"ytp-cards-shopping-active",Teb(a))},Seb=function(a,b){if(!g.lp(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Iw(),d=a.j?a.j.Af.Gf:a.Gf;
c&&d&&g.mx(c,[d]);a.j=b;g3(a)}(c=a.isInitialized&&a.Ib().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.Af.teaserDurationMs&&a.J.GC(!0,{teaserText:b.Af.teaserText,durationMs:b.Af.teaserDurationMs,onClickCommand:b.Af.onClickCommand});a.ib.isActive()||((!a.C||!a.Ca.isActive()&&a.La)&&Reb(a,b),a.ib.start(910+b.Af.teaserDurationMs))}},Reb=function(a,b){a.W.Eb?(b=new J2([0,
a.B.scrollTop],[0,b.YO.offsetTop],600,Zdb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.xx(a.W,!0),a.B.scrollTop=b.YO.offsetTop,g.xx(a.W,!1))},h3=function(a){return a.j&&a.j.Af?a.j.Af:a.cards[0]&&a.cards[0].Af?a.cards[0].Af:null},Jeb=function(a,b){return g.Tb(a.cards,function(c){return c.Af.id===b})},i3=function(a,b,c){Z2.call(this,a,b);
this.annotation=c;this.isActive=!1},Ueb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(Number(b.start_ms),Number(b.end_ms),a.annotation.id,function(){a.show()},function(){a.hide()})},j3=function(a,b,c){i3.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Veb=function(a,b){var c=c===void 0?0:c;
var d=Qdb(b).width;g.zm(b,d);c=new Xdb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Ydb);g.P(a,c);a.context.C.listen(c,"begin",function(){g.Fm(b,!0)});
c.play()},Yeb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.BY(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ha(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Fm(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.sm(l,"right",b.image_width+"px");g.fh(a.Ib(),l);a.C=new g.ep(function(){Web(a,h,l)},500);
g.P(a,a.C);a.context.j.listen(a.Ib(),"mouseover",function(){Xeb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Ib(),"mouseout",function(){a.C.start()})}},Xeb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Em(b);a.j||(b.style.width=g.ym(f.width,!0),c.style.width=g.ym(f.width,!0));g.sm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.sm(d,"right","1px");a.D=!0;g.Fm(b,!0);a.G=new g.ep(function(){g.mp(this.Ib(),"iv-branding-active")},0,a);
a.G.start()}},Web=function(a,b,c){g.op(a.Ib(),"iv-branding-active");
a.K=new g.ep(function(){g.Fm(b,!1);a.j||(c.style.width=g.ym(0,!0))},250);
a.K.start();a.D=!1},Zeb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.Y=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},$eb=function(a,b,c){i3.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.W=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.ep(function(){d.j.setAttribute("aria-hidden","true");g.Fm(d.C,!1);g.Fm(d.B,!0)},700,this);
g.P(this,this.G)},cfb=function(a,b,c){c.stopPropagation();
afb(a);bfb(a,b);a.j.focus()},dfb=function(a){a.isCollapsed||a.Z||a.D||(g.mp(a.Ib(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},afb=function(a){a.G.stop();
a.isCollapsed&&(g.pp(a.Ib(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Fm(a.B,!1),g.Fm(a.C,!0))},bfb=function(a,b){a.D||(a.D=g.Ai(function(){efb(this);
dfb(this)},b,a))},efb=function(a){a.D&&(g.Ma.clearTimeout(a.D),a.D=null)},ffb=function(a){this.J=a},Leb=function(a,b,c){b&&(c?k3(a,b.map(function(d){return g.Jo(d,c)})):k3(a,b))},k3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.w(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.$u(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},gfb=function(a){g.VX.call(this,a);
var b=this;this.oa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new ffb(this.player);this.D=new g.NF(this);this.G=this.N=null;this.events=new g.NF(this);this.ih=this.W=this.j=null;this.qa=[];g.P(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.b5,this);this.subscribe("resize",this.cM,this);this.player.U().La.subscribe("vast_info_card_add",this.l1,this);g.P(this,this.events);this.Aa=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.S({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.P(this,this.B);g.iS(this.player,this.B.element,4);this.B.hide();this.C=new g.S({I:"div",Ka:["ytp-iv-video-content"]});g.P(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Aa);this.C.element.appendChild(a);this.Gv()&&this.load();var c=this.createElement({I:"style"});(g.Sg("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.ih(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},hfb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Fm(a,!1);return a},ifb=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.xx(a.B,b);g.xx(a.C,b)},jfb=function(a,b,c){a.Z=!0;
a.G=g.Er(b,c)},kfb=function(a,b){for(var c={},d=g.w(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Sa(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(kfb(a,e))}return c},ofb=function(a){var b=a.player.getVideoData();
if(b.Ta){var c=a.player.U().La.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.tr(h)&&h.responseXML?h.responseXML:null)&&lfb(a,h)}};
g.gt()&&(d.onFinish=mfb(a,d.onFinish));d.postParams={ic_only:"1"};nfb(d,c);a.Z=!0;g.Er(b.Ta,d)}}},nfb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.GJ&&(a.postParams.ic_coll=b.GJ);b.ZO&&(a.postParams.ic_xml=b.ZO);b.rN&&(a.postParams.ic_track=b.rN)},pfb=function(a){var b=new g.S({I:"div"});
g.Fm(b.element,!1);var c=new Geb(a.player,b.element,l3(a));g.P(c,b);b.Ha(a.B.element);c.gI();return c},rfb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.oa=!0,qfb(a,b),b.headerText&&a.ih&&(c=g.Bx(b.headerText),a.ih.setAttribute("title",c))},l3=function(a){if(!a.W){var b=new $db(a);
g.P(a,b);var c=new g.Ck(a);g.P(a,c);a.W=new Zeb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Lj)}return a.W},lfb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.Iw();if(e){var f=g.Hw();f&&g.dr(g.bx)(void 0,e,f,[g.Fw(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=kfb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=T2(f.type,sfb),p=T2(f.style,tfb),q=peb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=veb;if(t==null)var u=null;else if(g.Ra(t)){l=[];for(var y=g.w(t),A=y.next();!A.done;A=y.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var G=f(t);u=G?[G]:[]}e=m&&n?new web(m,n,p,u,r):null}else e=null}catch(ea){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=hfb(f),M=null;switch(l.type){case "branding":if(f.player.U().Kd)break;f.B.element.appendChild(H);M=new j3(H,l3(f),l);break;case "promotion":g.iS(f.player,H,4),M=new $eb(H,l3(f),l)}M&&M.gI();if(f=M)g.P(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=pfb(a),g.P(a,a.j));if(e.type==="card"){H=a.j;var N=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(N)switch(f=e.tracking||{},f={NZ:f.impression,click:f.click,close:f.close,l3:f.teaser_impression,mN:f.teaser_click},l=e.tracking_params||{},M=null,N){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,uj:f,Xp:l.card?g.Fw(l.card):null,fk:l.teaser?g.Fw(l.teaser):null,Gf:l.icon?g.Fw(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:V2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};d3(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,uj:f,
Xp:l.card?g.Fw(l.card):null,fk:l.teaser?g.Fw(l.teaser):null,Gf:l.icon?g.Fw(l.icon):null,wI:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:V2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};d3(H,c);break;case "productListing":e.signin_url&&(M=V2({target:"current",value:e.signin_url}));N=[];for(var X=e.offers||[],V=0;V<X.length;V++)N.push(new Ceb(g.bg(X[V].merchant),
g.bg(X[V].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,uj:f,Xp:l.card?g.Fw(l.card):null,fk:l.teaser?g.Fw(l.teaser):null,Gf:l.icon?g.Fw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,SE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:V2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),sqa:M,rqa:e.signin_title?e.signin_title:void 0,qqa:e.signin_message?e.signin_message:void 0,offers:N,onClickCommand:null};d3(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,uj:f,Xp:l.card?g.Fw(l.card):
null,fk:l.teaser?g.Fw(l.teaser):null,Gf:l.icon?g.Fw(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,SE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:V2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};d3(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,uj:f,Xp:l.card?g.Fw(l.card):null,fk:l.teaser?g.Fw(l.teaser):null,Gf:l.icon?g.Fw(l.icon):null,wI:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:V2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},d3(H,c)}}else Heb(a.j,e);c=!0}}c&&
(E2(a.player),a.cM())},qfb=function(a,b){var c=!1;
a.j||(a.j=pfb(a),g.P(a,a.j));for(var d=g.w(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Ieb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.oR(f)||(c=a.j,d=b.headerText?g.Bx(b.headerText):"",g.kh(c.Lb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.Fw(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.Fw(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Gf=b.icon.infoCardIconRenderer.trackingParams?g.Fw(b.icon.infoCardIconRenderer.trackingParams):null,a.cM());E2(a.player)}},ufb=function(a,b,c,d,e){if(!a.player.U().Kd){var f=[];
b.navigationEndpoint&&g.Q(b.navigationEndpoint,g.hR)&&g.Q(b.navigationEndpoint,g.hR).browseId&&f.push(new seb("openUrl","click",new qeb("/channel/"+g.Q(b.navigationEndpoint,g.hR).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.Q(b.subscribeButton,
g.iR)){d.channel_id=g.Q(b.subscribeButton,g.iR).channelId;var l;b=g.Q(b.subscribeButton,g.iR);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Bx(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Bx(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Bx(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Bx(b.subscriberCountWithSubscribeText)));var m,n=((m=g.Q((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.x1))==null?void 0:m.url)||"";l={subscribeText:g.Bx(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.Bx(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new web(c,"branding","branding",f,d);l=hfb(a);a.B.element.appendChild(l);f=new j3(l,l3(a),f);f.gI();g.P(f,f);a.K[c]=f}},mfb=function(a,b){return function(){var c=g.Ca.apply(0,arguments);
a.Ia()||a.qa.push(g.Yo.Yi(function(){b.apply(null,g.x(c))}))}},vfb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.aS.prototype.GC=g.ba(35,function(a,b){var c=g.jY(this.yb());c&&c.GC(a,b)});
var G2={},H2=null;g.Za(J2,g.rp);g.k=J2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;I2(this);this.startTime=a=g.Ya();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.TL();this.jo("play");this.isPaused()&&this.jo("resume");this.j=1;var b=g.Va(this);b in G2||(G2[b]=this);Tdb();Udb(this,a);return!0};
g.k.stop=function(a){I2(this);this.j=0;a&&(this.progress=1);Vdb(this,this.progress);this.onStop();this.Is()};
g.k.pause=function(){this.isPlaying()&&(I2(this),this.j=-1,this.jo("pause"))};
g.k.xa=function(){this.j==0||this.stop(!1);this.jo("destroy");J2.Tf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.rO=function(){this.jo("animate")};
g.k.jo=function(a){this.dispatchEvent(new Wdb(a,this))};
g.Za(Wdb,g.Mh);g.Za(K2,J2);K2.prototype.C=function(){};
K2.prototype.rO=function(){this.C();K2.Tf.rO.call(this)};
K2.prototype.Is=function(){this.C();K2.Tf.Is.call(this)};
K2.prototype.TL=function(){this.C();K2.Tf.TL.call(this)};
g.Za(Xdb,K2);Xdb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.z($db,g.O);g.k=$db.prototype;g.k.listen=function(a,b,c,d){c=(0,g.Wa)(c,d||this.B);a=g.Bs(a,b,c);this.j.push(a);return a};
g.k.GG=function(a,b,c,d){c=(0,g.Wa)(c,d||this.B);a=Rdb(a,b,c);this.j.push(a);return a};
g.k.Lc=function(a){g.Cs(a);g.Xb(this.j,a)};
g.k.removeAll=function(){g.Cs(this.j);this.j.length=0};
g.k.xa=function(){this.removeAll();g.O.prototype.xa.call(this)};g.z(ceb,g.VX);g.k=ceb.prototype;g.k.load=function(){g.VX.prototype.load.call(this);if(!N2(this)){var a=g.XLa(this.player.getVideoData());a?(a=beb(a,deb(this)),O2(this,a,!1)):eeb(this)}};
g.k.unload=function(){O2(this,null);this.C&&(this.C.abort(),this.C=null);g.VX.prototype.unload.call(this)};
g.k.gi=function(a,b){return N2(this)?a==="loadCustomEndscreenRenderer"?(a=beb(b,"new"),O2(this,a),!0):null:null};
g.k.getOptions=function(){return N2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.jc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<wfb.length;f++){var h=Math.abs(b.width-wfb[f]);if(e===-1||d>=h)e=f,d=h}d=xfb[e];this.B&&g.sm(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Dm(e.element,m,f);g.zm(e.element,n,p);g.pp(e.element,yfb);m>256||f>256?g.mp(e.element,"ytp-ce-large-round"):m>96||f>96?g.mp(e.element,"ytp-ce-medium-round"):g.mp(e.element,"ytp-ce-small-round");g.pp(e.element,zfb);m=h.left+h.width/2;h=h.top+l/2;g.mp(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.pp(e.element,xfb);g.mp(e.element,d);(e=g.Wg(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.sm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")S2(this,this.endscreen.impressionUrls),(a=g.Iw())&&this.endscreen.visualElement&&g.kx(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.mp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.mp(b,"ytp-ce-shown");S2(this,c.impressionUrls);(b=g.Iw())&&g.kx(b,c.visualElement);this.player.U().N&&this.player.eb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.op(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.op(b,"ytp-ce-shown");this.player.U().N&&this.player.eb("endscreenelementhidden",a)}};
g.k.nda=function(a){var b=this;a.target===window&&(new g.ep(function(){for(var c=g.w(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.pp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var wfb=[346,426,470,506,570,640,853,1280,1920],xfb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),zfb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],yfb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var reb={Lha:"current",qka:"new"};var teb={CLOSE:"close",vka:"openUrl",SUBSCRIBE:"subscribe"},ueb={uha:"click",CLOSE:"close",Nia:"hidden",kla:"rollOut",lla:"rollOver",xla:"shown"};web.prototype.Ee=function(){var a=xeb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var tfb={Fga:"anchored",D4:"branding",CHANNEL:"channel",Kha:"cta",Qia:"highlightText",Eja:"label",PLAYLIST:"playlist",POPUP:"popup",Fla:"speech",SUBSCRIBE:"subscribe",Qla:"title",VIDEO:"video",zma:"website"},sfb={D4:"branding",hha:"card",Xha:"drawer",Pia:"highlight",Uja:"marker",Qka:"promotion",TEXT:"text",bna:"widget"};g.z(Z2,g.O);g.k=Z2.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.nE(a,b,{id:c,namespace:"annotations_module"});d&&this.Ta.set(a,d);e&&this.Wa.set(a,e);this.context.J.nf([a],1)};
g.k.gI=function(){this.context.B.subscribe("resize",this.BJ,this)};
g.k.Ib=function(){return this.element};
g.k.LN=function(a,b,c,d,e,f){if(this.kb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.ih(this.Ib())};
g.k.BJ=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=U2(a);if(f){var h=Eeb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Jf||!1,n=g.jr(f||"");m&&n&&(n.v||n.list)?e.context.J.Fp(n.v,b,n.list,!1):g.bz(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);k3(this.context.logger,c,l,d);Deb(f)||(c=g.Iw(),d=b.itct,c&&d&&g.nx(c,g.Fw(d)))}};
g.k.xa=function(){this.Ta.clear();this.Wa.clear();g.O.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.z(Geb,Z2);g.k=Geb.prototype;g.k.xu=function(){this.qa&&d3(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Em(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.BJ=function(){var a=this.isAvailable();g.Fm(this.Ib(),a);g.qp(this.context.J.getRootNode(),g.G_.IV_DRAWER_ENABLED,a);E2(this.J)};
g.k.destroy=function(){this.J.GC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.tv(this.oa);g.Is(this.Na);this.Ua&&this.Ua.dispose();this.G&&this.G.dispose();Z2.prototype.destroy.call(this)};
g.k.nJ=function(){var a=this,b=g.Yg("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.Z7,this);this.context.j.listen(this.B,"touchend",function(){a.Ca.start()});
this.context.j.listen(this.B,"scroll",this.y8,this);this.context.B.subscribe("onHideControls",function(){a.La=!0});
this.context.B.subscribe("onShowControls",function(){a.La=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.La=g.lp(a.J.getRootNode(),"ytp-autohide")});
this.oa.push(g.rv("iv-button-shown",this.baa,this));this.oa.push(g.rv("iv-button-hidden",this.aaa,this));Neb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Ub(this.cards,function(c){return a.Af.startMs>c.Af.startMs||a.Af.startMs===c.Af.startMs&&a.Af.timestamp>=c.Af.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.Z7=function(){if(this.C){k3(this.context.logger,h3(this).uj.close);var a=g.Iw();a&&this.N&&g.nx(a,this.N);c3(this)}};
g.k.y8=function(){g.qp(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.baa=function(){var a=g.Iw(),b=h3(this);b=b?b.Gf:this.Gf;a&&b&&g.lx(a,[b])};
g.k.aaa=function(){var a=g.Iw(),b=h3(this);b=b?b.Gf:this.Gf;a&&b&&g.mx(a,[b])};
g.k.a5=function(){var a=h3(this);k3(this.context.logger,a.uj.l3);var b=g.Iw();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.fk&&c.push(a.fk);a.Gf&&c.push(a.Gf);c.length>0&&g.lx(b,c)}else g.lx(b,[a.fk,a.Gf])};
g.k.daa=function(){var a=g.Iw(),b=h3(this);a&&b&&g.mx(a,[b.fk])};
g.k.Z4=function(a){var b=h3(this),c=g.Iw();this.j?a?(a=this.context.logger,k3(a,b.uj.mN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.fk&&g.nx(c,b.fk)):(a=this.context.logger,k3(a,b.uj.mN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Gf&&g.nx(c,b.Gf)):(a=this.context.logger,k3(a,b.uj.mN),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Gf&&g.nx(c,this.Gf))};g.z(i3,Z2);i3.prototype.gI=function(){Z2.prototype.gI.call(this);Ueb(this)};
i3.prototype.show=function(){Z2.prototype.show.call(this);var a=g.Iw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.lx(a,[g.Fw(b.itct)])};
i3.prototype.hide=function(){Z2.prototype.hide.call(this);var a=g.Iw(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.mx(a,[g.Fw(b.itct)])};g.z(j3,i3);
j3.prototype.bz=function(){g.mp(this.Ib(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Fm(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ib().appendChild(b);var c=this.annotation.Ee();c&&$2(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||Yeb(this,
a)};
j3.prototype.show=function(){if(!this.isActive&&(i3.prototype.show.call(this),this.N||(this.bz(),this.N=!0),g.Fm(this.Ib(),!0),this.isActive=!0,this.B)){try{Veb(this,this.B)}catch(a){}g.mp(this.context.J.getRootNode(),"ytp-branding-shown")}};
j3.prototype.hide=function(){this.isActive&&(i3.prototype.hide.call(this),g.Fm(this.Ib(),!1),this.isActive=!1,g.op(this.context.J.getRootNode(),"ytp-branding-shown"))};
j3.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);i3.prototype.destroy.call(this)};g.z($eb,i3);g.k=$eb.prototype;
g.k.bz=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ib().setAttribute("aria-hidden","true");this.Ib().setAttribute("aria-label","Promotion");this.Ib().tabIndex=0;var e=this.annotation.Ee(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&$2(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Lf(f,U2(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",va:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",va:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&$2(this,
this.Ib(),e,this.annotation.id,b.session_data,void 0,c)}g.mp(this.j,"iv-click-target");e&&$2(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",va:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.mp(this.j,"iv-click-target"),e&&$2(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){cfb(a,5E3,q)});
c.appendChild(this.B);g.Fm(this.B,!1);this.context.j.listen(this.Ib(),"mouseover",this.a$,this);this.context.j.listen(this.Ib(),"mouseout",this.Z9,this);this.context.j.listen(this.Ib(),"touchend",function(q){cfb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.V9:this.U9,this);c.appendChild(this.C);g.np(this.Ib(),d);h&&(g.fh(this.Ib(),h),n&&h.appendChild(n));g.fh(this.Ib(),this.N);g.fh(this.Ib(),c)};
g.k.show=function(){this.isActive||(i3.prototype.show.call(this),this.W||(this.bz(),this.W=!0),g.Fm(this.Ib(),!0),g.Ai(function(){g.op(this.Ib(),"iv-promo-inactive")},100,this),this.Ib().removeAttribute("aria-hidden"),this.isActive=!0,efb(this),afb(this),bfb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.mp(this.Ib(),"iv-promo-inactive"),this.isActive=!1,this.Ib().setAttribute("aria-hidden","true"))};
g.k.LN=function(a,b,c,d,e,f){return this.isCollapsed?!1:i3.prototype.LN.call(this,a,b,c,d,e,f)};
g.k.a$=function(a){this.Z=!0;cfb(this,500,a)};
g.k.Z9=function(){this.Z=!1;dfb(this)};
g.k.U9=function(a){a.stopPropagation();this.hide()};
g.k.V9=function(a){a.stopPropagation();efb(this);this.isCollapsed=!0;g.mp(this.Ib(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();i3.prototype.destroy.call(this)};g.z(gfb,g.VX);g.k=gfb.prototype;g.k.gi=function(a,b){if(!vfb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.b1(b))&&lfb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Keb(this.j,b),E2(this.player)),!0}return null};
g.k.getOptions=function(){return vfb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Gv=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.CR(b)||this.player.isMutedByEmbedsMutedAutoplay()?!1:c===1&&!b.s2||a.La.get(b.videoId)||g.pR(b)||g.qR(b)?!0:!1};
g.k.cM=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Dm(this.C.element,a.width,a.height);g.zm(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Fo();a=this.j;b=b.width;g.qp(a.D,"iv-drawer-small",b<=426);g.qp(a.D,"iv-drawer-big",b>=1280)}};
g.k.b5=function(a){ifb(this,a.state);g.U(a.state,2)&&(this.El()&&this.Up()&&this.player.getPresentingPlayerType()!==2&&this.HC(!1),this.GC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.tr(h)&&h.responseXML?h.responseXML:null)&&(lfb(b,h),g.mp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.VX.prototype.load.call(this);ifb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.gt()&&(a=mfb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().La.get(d);f&&nfb(e,f);f=f&&(f.ZO||f.GJ);if(!c.nw||f)c.Ta?jfb(this,c.Ta,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.oR(h))&&!b.oa&&rfb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.iS(this.player,this.C.element,4);this.cM();(f=g.pR(c))&&qfb(this,f);(f=g.qR(c))&&f.featuredChannel&&ufb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.ih=g.Yg("ytp-cards-button",this.player.getRootNode());g.oR(c)&&rfb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ta&&jfb(this,b.Ta,a)};
g.k.unload=function(){this.player.jf("annotations_module");for(var a=g.w(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.W=null;this.j&&(this.j.destroy(),this.j=null,E2(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.oa=!1;this.K={};this.B.hide();g.VX.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.l1=function(a){a===this.player.getVideoData().videoId&&(this.loaded?ofb(this):this.load())};
g.k.El=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.oa};
g.k.Up=function(){return!!this.j&&this.j.C};
g.k.HC=function(a,b,c){b=b===void 0?!1:b;this.El();this.j&&(a?c?b3(this.j,c,b):b3(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):c3(this.j))};
g.k.GC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().La.unsubscribe("vast_info_card_add",this.l1,this);g.op(this.player.getRootNode(),g.G_.IV_DRAWER_OPEN);for(var a=this.qa,b=g.Yo,c=0,d=a.length;c<d;c++)b.Ej(a[c]);this.qa.length=0;g.VX.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.P(this,a);return a.element};g.UX("annotations_module",gfb);g.UX("creatorendscreen",ceb);})(_yt_player);
