(function(g){var window=this;'use strict';var Cfb=function(a,b,c){var d;g.J(function(e){switch(e.j){case 1:var f=b;a.Y.L("web_player_pt_tt")?(f=g.jr(f).exp||"",f=f.includes("xpv")||f.includes("xpe")):f=!1;if(!f){e.Da(2);break}if(a.videoData.Ew){e.Da(3);break}g.va(e,4);return g.F(e,a.D.promise,6);case 6:g.wa(e,3);break;case 4:return g.xa(e),e.return();case 3:d={potc:"1",pot:a.videoData.Ew},b=g.kr(b,d);case 2:a.j=g.Er(b,c),g.ua(e)}})},m3=function(a){a.isActive()||a.start()},Dfb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},
Efb=function(a,b){var c=new g.TP;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},Ffb=function(a,b){var c,d,e;
return g.J(function(f){if(f.j==1)return c=a+"|"+b,g.F(f,g.fu(),2);if(f.j!=3){d=f.B;if(!d)throw g.Ct("gct");return g.F(f,g.kQ(d),3)}e=f.B;return f.return(e.get("captions",c))})},Gfb=function(a,b,c){Ffb(a,b).then(function(d){d&&c(d.trackData,new g.TP(d.metadata))})},Jfb=function(a){if(!Hfb.test(a))throw Error("'"+a+"' is not a valid hex color");
a.length==4&&(a=a.replace(Ifb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Kfb=function(){var a=void 0;
a=a===void 0?{}:a;var b="suggest_correction"in g.ocb?g.ocb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={yG:c.yG};c.yG=d;var e=function(f){return function(){return String(a[f.yG])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.yG+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.yG,"gi"),e)}return b},Lfb=function(){return g.Ns("yt-player-caption-display-settings")},n3=function(){this.segments=[]},Mfb=function(a,b){var c=g.fc(a.segments,b);
c>=0||c<0&&(-c-1)%2===1||(c=-c-1,c>0&&b-a.segments[c-1]===1&&c<a.segments.length&&a.segments[c]-b===1?(g.Wb(a.segments,c),g.Wb(a.segments,c-1)):c>0&&b-a.segments[c-1]===1?a.segments[c-1]=b:c<a.segments.length&&a.segments[c]-b===1?a.segments[c]=b:(g.cc(a.segments,c,0,b),g.cc(a.segments,c+1,0,b)))},Nfb=function(a,b,c,d,e,f){g.O.call(this);
this.policy=a;this.player=b;this.oa=c;this.Z=d;this.G=e;this.W=f;this.D=new n3;this.K=-1;this.C=this.B=this.j=null;this.N=new g.ep(this.F_,1E3,this);this.events=new g.NF(this);g.P(this,this.N);g.P(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.VB);this.VB();this.F_()},Ofb=function(a){return a.j&&a.j.Rf?a.j.Rf+a.player.Ac()<a.player.getCurrentTime():!1},Pfb=function(a,b){if(a.policy.Am&&a.player.ou()){var c=g.nN(b,a.policy,{});
c.set("pot",a.player.ou());c=c.Ee()}else c=g.nN(b,a.policy,{}).Ee();var d={format:"RAW",withCredentials:!0};if(a.policy.La){d.method="POST";var e=b.D;e&&Object.keys(e).length>0?d.postBody=g.rB(e,g.zL):d.postBody=(0,g.QT)([120,0])}a.G&&(d.responseType="arraybuffer");a.C=g.Ir(c,d,3,100).then(function(f){a:{f=f.xhr;a.Ia();if(a.B){var h=!(a.G?f.response:f.responseText)||f.status>=400,l=g.lIa(f);if(l){f=g.nN(a.B,a.policy,{});a.B.Pl(f,l);Pfb(a,a.B);break a}h?a.player.ma("capfail",{status:f.status}):(a.player.Lh().hg("fcb_r"),
l=a.B.gb[0].Oa,a.Z!=null&&a.K!==l&&(h=a.B.gb[0],a.G?a.Z(f.response,(h.startTime+a.player.Ac())*1E3):a.Z(f.responseText,(h.startTime+a.player.Ac())*1E3),a.K=l))}a.B=null;a.C=null}}).al(function(f){a.B=null;
a.C=null;var h;a.player.ma("capfail",{status:(h=f.xhr)==null?void 0:h.status})});
a.B=b;Mfb(a.D,a.B.gb[0].Oa)},o3=function(a,b){g.YX.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.K=!1;this.N=g.JD(this.J.U())&&!this.j.isManifestless},Rfb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.c0a(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Edb.get(e);q==null&&(q=Qfb[e]||Qfb[e.replace(/-/g,"_")],g.Edb.set(e,q));h=q||h}c.push(new g.TP({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
Sfb=function(a,b){return b!=null&&b in a.j.j?a.j.j[b]:null},Tfb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.c0a(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},p3=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Qe);a.params.Qe&&Object.assign(r,a.params.Qe);Object.assign(r,c.Qe);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Qe=r;var t=q.Ti===1,u=[{I:"span",S:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],y,A,C;(l=l.bb("caption_edit_on_hover")&&((y=n.getVideoData().getPlayerResponse())==null?void 0:(A=y.captions)==null?void 0:(C=A.playerCaptionsTracklistRenderer)==null?void 0:C.openTranscriptCommand))&&
u.unshift({I:"button",S:"caption-edit",X:{tabindex:"0","aria-label":Kfb()},V:[{I:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.S.call(this,{I:"div",S:"caption-window",X:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:u});var G=
this;this.K=[];this.Fa=!1;this.B=a;this.La=this.Ja=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=f*.96;this.maxHeight=h*.96;this.j=q;this.wc=c;this.qa=b;this.D=this.Ea("captions-text");this.Ob=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Ua=Ufb(d,e,f,h);this.pc=m;l&&(this.G=this.Ea("caption-edit"),this.T(this.G,"click",function(){G.pc()}));
this.type=0;this.Wa=this.Ua*Vfb(r);this.Ab=p;a=new g.yX(this.element,!0);g.P(this,a);a.subscribe("dragstart",this.e5,this);a.subscribe("dragmove",this.d5,this);a.subscribe("dragend",this.c5,this);this.ib=this.Va=this.rb=this.kb=0;a="";this.j.windowOpacity&&(a=Jfb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:this.j.isVisible===!1?"none":"","text-align":Wfb[this.j.textAlign]};this.Ob&&(b["border-radius"]=a?this.Wa/8+"px":"");(this.C=
this.B.params.Ti===2||this.B.params.Ti===3)&&Xfb(this,this.element);g.sm(this.element,b);if(p){var H;(H=this.element.parentElement)==null||H.style.setProperty("--caption-window-color",a)}switch(this.j.Lm){case 0:case 1:case 2:g.mp(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.mp(this.element,"ytp-caption-window-bottom")}},Xfb=function(a,b){var c="vertical-rl";
a.j.KU===1&&(c="vertical-lr");g.um&&(c=c==="vertical-lr"?"tb-lr":"tb-rl");g.sm(b,"-o-writing-mode",c);g.sm(b,"-webkit-writing-mode",c);g.sm(b,"writing-mode",c);g.sm(b,"text-orientation","upright");g.mp(b,"ytp-vertical-caption");a.B.params.Ti===3&&(g.sm(b,"text-orientation",""),g.sm(b,"transform","rotate(180deg)"))},Vfb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(a.offset===0||a.offset===2)b*=.8;return b},Yfb=function(a,b){var c={},d=b.background?b.background:a.j.Qe.background;
if(b.backgroundOpacity!=null||b.background){var e=b.backgroundOpacity!=null?b.backgroundOpacity:a.j.Qe.backgroundOpacity;d=Jfb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ob&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Wa/8+"px")}if(b.fontSizeIncrement!=null||b.offset!=null)c["font-size"]=a.Ua*Vfb(b)+"px";d=1;e=b.color||a.j.Qe.color;if(b.color||b.textOpacity!=null)e=Jfb(e),d=b.textOpacity==null?a.j.Qe.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;f===0&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.aP&&(h=e=b.aP);var l=a.Ua/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=window.devicePixelRatio>=2?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;p<5;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Wr()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;e==null&&(e=a.j.Qe.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}b.fontFamily===7&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]=
"underline");b.u$&&(c.visibility="hidden");b.LZ===1&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.FP||g.At,a.B.params.Ti===3?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(b.vp===1||b.vp===2||b.vp===3||b.vp===4||b.vp===5)if(g.FP)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.vp){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},q3=function(a){a=a.split("px");
return a.length>0?(a=Number(a[0]))?a:0:0},Zfb=function(a){a.N=g.dh("SPAN");
g.sm(a.N,{display:"block"});g.mp(a.N,"caption-visual-line");a.D.appendChild(a.N)},$fb=function(a,b){var c=g.dh("SPAN");
g.sm(c,{display:"inline-block","white-space":"pre-wrap"});g.sm(c,Yfb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.sm(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.sm(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},agb=function(a,b,c){a.Fa=a.Fa||!!c;
var d={};Object.assign(d,a.j.Qe);Object.assign(d,c||b.j);Object.assign(d,a.wc.Qe);(c=!a.N)&&Zfb(a);for(var e=a.Ja&&a.La&&g.Kg(d,a.La)?a.Ja:$fb(a,d),f=typeof b.text==="string",h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=l>0||!b.append,n=h[l];m&&!c?(Zfb(a),e=$fb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.eh(n):n),f||n.tagName!=="RUBY"||n.childElementCount!==4||g.FP||!g.vm(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.vm(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.$g?g.sm(e,m,"1em"):g.sm(e,m,"0.5em")))}a.La=d;a.Ja=e;a.K.push(b)},Ufb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>c*1.3&&(a=480),e=c/a*16);return e},cgb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new bgb(this);this.G=new bgb(this);this.j=[];this.clear()},wgb=function(a,b,c){if(a===255&&b===255||!a&&!b)return{Ww:a,
Mt:b,result:0};a=vgb[a];b=vgb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.xe()&&c.Mt===d;if(d)return{Ww:a,Mt:b,result:1}}else if(b&128&&1<=a&&a<=31)return{Ww:a,Mt:b,result:2};return{Ww:a,Mt:b,result:3}},ygb=function(a,b,c,d){b===255&&c===255||!b&&!c?(++a.C===45&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,xgb(a.D,b,c,d))},zgb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return h===0?e.order-f.order:h});
for(var c=g.w(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,d.type===0?ygb(a,d.OX,d.PX,b):d.type===1&&a.B&496&&xgb(a.G,d.OX,d.PX,b);a.j.length=0},r3=function(){this.type=0},s3=function(){this.state=this.Mt=this.Ww=0},Agb=function(){this.timestamp=this.j=0},t3=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new r3;for(a=this.C=0;a<=15;a++){this.B[a]=[];for(var b=0;b<=32;b++)this.B[a][b]=new Agb}},u3=function(a,b){if(a.style.type===3){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;m<=15;++m){for(var n=!1,p=d?d:1;p<=32;++p){var q=a.B[m][p];
if(q.j!==0){c===0&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((q.j===0||p===32)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;h<=15;++h)for(l="",m=1;m<=32;++m)if(p=a.B[h][m],q=p.j,q!==0&&(c===0&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),m===32||q===0)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},Fgb=function(a,b){switch(a){case 0:return Bgb[(b&127)-32];
case 1:return Cgb[b&15];case 2:return Dgb[b&31];case 3:return Egb[b&31]}return 0},v3=function(a){return a.B[a.row][a.col]},w3=function(a,b,c){b>=2&&a.col>1&&(--a.col,v3(a).j=0);
var d=v3(a);d.timestamp=a.D.time+0;d.j=Fgb(b,c);a.col<32&&a.col++},Ggb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;f<=32;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},x3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;e<=32;e++)a.B[b+d][e].reset()},Hgb=function(a){a.row=a.j>0?a.j:1;
a.col=1;x3(a,0,15)},Igb=function(a){this.C=a;
this.G=0;this.style=new r3;this.K=new t3(this.C);this.N=new t3(this.C);this.text=new t3(this.C);this.B=this.K;this.D=this.N;this.j=this.B},Jgb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:a.style.get()===4&&d.j>0||(u3(d,c),Hgb(a.B),Hgb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(u3(d,c),x3(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Kgb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},Lgb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},bgb=function(a){this.j=a;
this.G=0;this.C=new Igb(this.j);this.K=new Igb(this.j);this.B=new s3;this.D=this.C},xgb=function(a,b,c,d){a.B.update();
b=wgb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Ww;c=b.Mt;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&w3(a,0,b),c&96&&w3(a,0,c),b!==0&&c!==0&&a.style.type===3&&u3(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.Ww=e,b.Mt=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(b.style.type===4?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(b.style.type!==4?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?((c&14)>>1)*4:0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Ggb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,f>0&&(b+=f,e-=f)):(f=f+e-h,f>0&&(e-=f));x3(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:w3(b.j,0,32);break a;case 48:c===57?(d=b.j,v3(d).j=0,d.col<32&&d.col++):w3(b.j,1,c&15)}break;case 2:c&32&&w3(b.j,2,c&31);break;case 3:c&32&&w3(b.j,3,c&31);break;case 4:case 5:if(32<=c&&c<=47)switch(c){case 32:Kgb(b);
break;case 33:d=b.j;d.col>1&&(--d.col,v3(d).j=0);break;case 36:d=b.j;b=v3(d);for(a=0;a<=15;a++)for(c=0;c<=32;c++)if(d.B[a][c]===b){for(;c<=32;c++)d.B[a][c].reset();break}break;case 37:Jgb(b,2,d);break;case 38:Jgb(b,3,d);break;case 39:Jgb(b,4,d);break;case 40:w3(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Hgb(d);Lgb(b);break;case 43:Lgb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:u3(a,
d)}x3(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(a.row<15){++a.row;a.col=1;break b}break;case 3:}a.j<2&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;u3(a,d);Ggb(a,b,b+1,a.j-1);x3(a,a.row,1)}break;case 46:x3(b.D,0,15);break;case 47:u3(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,Kgb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,(d.col+=c&3)>32&&(d.col=32)}}},Mgb=function(){},y3=function(a,b,c,d,e,f,h){f=f===void 0?!1:f;
h=h===void 0?null:h;g.nE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},Ogb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(m.gg===1){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Ngb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new y3(a,b,e,c,l,d,m)}switch(m.gg){case 9:case 10:m.vp=1;break;case 11:m.vp=2;break;case 12:m.vp=3;break;case 13:m.vp=4;break;case 14:m.vp=5}return new y3(a,b,e,c,l.textContent||"",d,m)},Ngb=function(a,b,c,d,e){var f=g.Wr(),h=
f?g.dh("DIV"):g.dh("RUBY"),l=g.dh("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.dh("DIV"):g.dh("RP");a.textContent=b;h.appendChild(a);b=f?g.dh("DIV"):g.dh("RT");b.textContent=c;h.appendChild(b);c=e.gg;if(c===10||c===11||c===12||c===13||c===14)if(g.sm(b,"text-emphasis-style","filled circle"),g.sm(b,"text-emphasis-color","currentcolor"),g.sm(b,"webkit-text-emphasis","filled circle"),e.gg===11||e.gg===13)g.sm(b,"webkit-text-emphasis-position","under left"),g.sm(b,"text-emphasis-position","under left");c=!0;if(e.gg===4||e.gg===7||e.gg===12||
e.gg===14)g.sm(h,"ruby-position","over"),g.sm(h,"-webkit-ruby-position","before");else if(e.gg===5||e.gg===6||e.gg===11||e.gg===13)g.sm(h,"ruby-position","under"),g.sm(h,"-webkit-ruby-position","after"),c=!1;e=f?g.dh("DIV"):g.dh("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.sm(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.sm(f,"display","none"),f=f.nextElementSibling,g.sm(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.sm(h.lastElementChild,"display","none"),d?(g.sm(h,"padding-top","0.6em"),g.sm(f,"top","0")):(g.sm(h,"padding-bottom","0.6em"),g.sm(f,"bottom","0")));return h},z3=function(){g.O.apply(this,arguments)},A3=function(a,b,c,d,e){g.nE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Pgb=function(a){var b="_"+B3++;
return new A3(0,0x8000000000000,0,b,a)},C3=function(a){z3.call(this);
this.C=a;this.pens={};this.N={};this.Z={};this.D="_"+B3++;this.K={};this.B=this.j=null;this.G=!0},D3=function(a,b){a=a.getAttribute(b);
if(a!=null)return Number(a)},E3=function(a,b){a=a.getAttribute(b);
if(a!=null)return a==="1"},F3=function(a,b){a=D3(a,b);
return a!==void 0?a:null},H3=function(a,b){a=a.getAttribute(b);
if(a!=null)return G3.test(a),a},Qgb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=F3(b,"mh");a!=null&&(c.JB=a);a=F3(b,"ju");a!=null&&(c.textAlign=a);a=F3(b,"pd");a!=null&&(c.Ti=a);a=F3(b,"sd");a!=null&&(c.KU=a);a=H3(b,"wfc");a!=null&&(c.windowColor=a);b=D3(b,"wfo");b!==void 0&&(c.windowOpacity=b/255);return c},Rgb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=F3(b,"ap");a!=null&&(c.Lm=a);a=D3(b,"cc");a!=null&&(c.Pt=a);a=D3(b,"ah");a!=null&&(c.Jk=a);a=D3(b,"rc");a!=null&&(c.Qs=a);b=D3(b,"av");b!=null&&(c.yp=b);return c},Sgb=function(a,b,c,d){var e={};
Object.assign(e,Rgb(a,b));Object.assign(e,Qgb(a,b));d?g.Kg(e,a.C)?(d=a.D,e=a.C):d="_"+B3++:d=b.getAttribute("id")||"_"+B3++;a=D3(b,"t")+c;b=D3(b,"d")||0x8000000000000;if(e.Ti===2||e.Ti===3)c=e.Qs,e.Qs=e.Pt,e.Pt=c;return new A3(a,b,0,d,e)},I3=function(a){z3.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},J3=function(a){a=g.qg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Tgb=function(a,b,c,d,e){d===0&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;a!==void 0&&(f.Qs=a);b=b.ccColCount;b!==void 0&&(f.Pt=b);if(f.Ti===2||f.Ti===3)b=f.Qs,f.Qs=f.Pt,f.Pt=b;return new A3(c,d,0,e,f)},K3=function(a,b,c,d){g.YX.call(this,a);
this.videoData=b;this.audioTrack=c;this.Sa=d;this.G=b.Bw},L3=function(a,b,c,d,e,f,h,l,m,n){p3.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},M3=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},N3=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},O3=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},P3=function(a,b){z3.call(this);
this.B=a;this.C=b;this.track=this.C.languageName==="CC3"?4:0;this.j=new cgb;this.j.B=1<<this.track},Vgb=function(a){if(typeof a==="string")return!1;
a=new M3(a,8,0);return Ugb(a)},Ugb=function(a){if(!(a.byteOffset<a.j.byteLength)||O3(a)!==1380139777)return!1;
a.version=N3(a);if(a.version>1)return!1;N3(a);N3(a);N3(a);return!0},Q3=function(a,b,c,d,e,f,h,l,m,n){p3.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Aa=[];this.oa=this.W=this.Na=0;this.Ca=NaN;this.Gb=0;this.Sb=null;this.Ta=new g.ep(this.wca,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.yX(this.element,!0),g.P(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.mp(this.element,"ytp-caption-window-rollup");g.P(this,this.Ta);g.sm(this.element,"overflow","hidden")},Wgb=function(a,b){if(!b)return"";
a.C&&a.B.params.KU!==1&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},Xgb=function(a){a.Aa=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Qs,c=0,d=0,e=a.Aa.length-1;c<b&&e>-1;){var f=a.Aa[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.W=d;b=Math;c=b.max;isNaN(a.Ca)&&((d=a.j.Pt)?(e=g.dh("SPAN"),g.kh(e,"\u2013".repeat(d)),g.sm(e,Yfb(a,a.j.Qe)),a.D.appendChild(e),a.Ca=e.offsetWidth,a.D.removeChild(e)):a.Ca=0);d=a.D;a.oa=c.call(b,a.Ca,a.Gb,(a.C?d.offsetHeight:d.offsetWidth)+1)},Ygb=function(a,b){Xgb(a);
var c=a.Aa.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.W-c;if(c!==a.Na){var d=c>0&&a.Na===0,e=c<a.Na;b||isNaN(c)||d||!e||(g.mp(a.element,"ytp-rollup-mode"),g.fp(a.Ta));g.sm(a.D,"transform",Wgb(a,c));a.Na=c}Xgb(a)},R3=function(){z3.call(this)},Zgb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(p.nodeType===3)p=new y3(b,c,d,e.id,p.nodeValue,f||n>0,g.Ig(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Zgb(a,b,c,d,e,!0,p,q,m)}}},$gb=function(a){var b=a.split(":");
a=0;b=g.w(b);for(var c=b.next();!c.done;c=b.next())a=a*60+Number(c.value);return a*1E3},ahb=function(a,b,c,d){d=Object.assign({JB:0},d);
return new A3(a,b,c,"_"+B3++,d)},S3=function(a,b){g.O.call(this);
this.J=a;this.Y=b;this.j=null;this.B=this.J.MA();this.logger=new g.ET("caps")},bhb=function(a){if(typeof a==="string"||Vgb(a))return a;
var b=new DataView(a);if(b.byteLength<=8||b.getUint32(4)!==1718909296)return"";b=g.sM(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.WA(a)},dhb=function(a,b,c){if(typeof b==="string"||Vgb(b))return[{trackData:b,
EU:c}];var d=new DataView(b);if(d.byteLength<=8||d.getUint32(4)!==1718909296)return[];var e=g.jEa(d);if(a.B&&e){var f=g.bEa(e),h=g.cEa(e);e=e.qj;f&&e&&a.B.BI(e,f,h)}a=g.BM(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.WA(e),f.push({trackData:e,EU:c+h*1E3});chb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},chb=function(a,b,c){var d=g.sM(a,0,1836476516),e=9E4;
d&&(e=g.tM(d)||9E4);d=0;for(var f=g.BM(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.sM(a,l.dataOffset,1953653094))&&(l=g.sM(a,l.dataOffset,1952867444))&&(l=g.zM(l)/e*1E3,h===0&&(d=l),b[h].EU=l-d+c||c*h*1E3)}},ehb=function(a,b,c,d,e){if(!Vgb(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new P3(e,b));return a.j.fp(c,d)},fhb=function(a,b,c){a.j||(a.j=new R3);
a=a.j.fp(b,c);Math.random()<.01&&g.Rw(Error("Deprecated subtitles format in web player: WebVTT"));return a},hhb=function(a,b,c,d){if(c[0]==="{")try{return a.j||(a.j=new I3(ghb(b))),a.j.fp(c,d)}catch(f){return g.Qw(f),[]}var e=g.b1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if(e.firstChild.tagName==="timedtext"){if(Number(e.firstChild.getAttribute("format"))===3)return a.j||(a.j=new C3(ghb(b),a.Y)),a.j.fp(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if(e.firstChild.tagName==="transcript")throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},ghb=function(a){var b=
{};
if(a=g.WP(a))b.lang=a,g.$ab.test(a)&&(b.Ti=1);return b},T3=function(a){g.VX.call(this,a);
var b=this;this.J=a;this.Y=this.J.U();this.videoData=this.J.getVideoData();this.rb=this.J.ob();var c;this.ib=(c=this.J.getVideoData(1))==null?void 0:g.LQ(c);this.C={Qe:{}};this.G={Qe:{}};this.Fa=[];this.Aa={};this.Ua={};this.N=!1;this.Ob=g.zR(this.videoData);this.Va=g.d0a(this.videoData,this.J);this.Gb=!!this.videoData.captionTracks.length;this.Sb=!!this.videoData.Zd;this.Ta=this.Y.controlsType==="3";this.j=this.Z=this.W=this.Na=this.kb=null;this.Wa=new S3(this.J,this.Y);this.B=null;this.oa=new g.NF(this);
this.K=new g.S({I:"div",S:"ytp-caption-window-container",X:{id:"ytp-caption-window-container"}});this.qa={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.Pp("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Gp(d));this.storage=c;var e;this.Lb=!((e=a.De())==null||!e.tI());this.D=ihb(this);this.Ca=!this.D&&this.Ta&&this.Lb&&this.Va;g.P(this,this.Wa);this.D?this.La=this.Ja=null:(this.Ja=new g.dp(this.WU,void 0,this),g.P(this,this.Ja),this.La=new g.ep(this.eea,2E3,this),g.P(this,
this.La));g.P(this,this.oa);g.iS(this.player,this.K.element,4);g.P(this,this.K);this.oa.T(a,"contentPoTokenReady",this.aH);this.D||this.oa.T(a,"resize",this.XU);(this.Ab=g.mP(this.Y)&&!g.ws()&&!this.J.isFullscreen()&&!this.D&&!this.Ca)&&this.oa.T(a,"resize",this.Fba);this.oa.T(a,"onPlaybackAudioChange",this.Raa);this.oa.T(a,g.pE("captions"),function(f){b.onCueRangeEnter(f)});
this.oa.T(a,g.qE("captions"),function(f){b.onCueRangeExit(f)});
this.ib&&this.oa.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
jhb(this,Lfb()||{});this.player.zd("onCaptionsModuleAvailable")},mhb=function(a){if(a.Y.Lb===1||a.videoData.tD===1||g.fR(a.videoData,"yt:cc")==="alwayson")return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(a.Y.Lb===2){if(g.CP(a.Y))var c=khb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(c!=null)return!!c}c=Dfb(a.player.getAudioTrack(),g.CP(a.Y));var d=g.fR(a.videoData,"yt:cc");if(lhb(a)===void 0){if(c==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return d?d==="on":!0;if(c==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return d==="on"}else return d==="on";return b==="ON"||g.fR(a.videoData,
"yt:cc")==="on"},U3=function(a,b){if(a.B&&(b===void 0||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||a.B==="FORCED_ON"},lhb=function(a){var b=void 0,c=g.Us(g.Ts(),65);
if(g.CP(a.Y)&&c!=null){if(khb(a)!=null)return!1;b=!c}return b},nhb=function(a){var b;
a.Ob?b=new K3(a.Y,a.videoData,a.getAudioTrack(),a.player):a.Va?b=new o3(a.videoData.j,a.player):a.Gb?b=new g.ZX(a.Y,a.videoData,a.getAudioTrack()):b=new g.$X(a.Y,a.videoData.Zd,a.videoData.videoId,g.eMa(a.videoData),a.videoData.Ln,a.videoData.eventId);return b},W3=function(a,b){if(a.j){if(a.Z&&a.Z.D)return a.Z.D;
g.sR(a.videoData)&&(b=!0);b||(b=a.Sb?!1:a.Gb?!1:!0);b=b||ohb(a);b=g.WX(a.j.B,b);var c=null;if(g.CP(a.Y)){var d=a.J.isInline()?void 0:g.Ns("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.fR(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.WP(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.WP(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.G,
e.length))for(e=g.w(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.fR(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.WP(b[f])===d[e])return b[f];d=null;a.Z&&a.Z.C&&(d=a.Z.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||V3(a));d&&c&&g.WP(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=Efb(d,c));return d}return null},V3=function(a){return a.Z&&a.Z.j},X3=function(a){var b=V3(a);
return!!b&&a.B===b},phb=function(a){var b=Dfb(a.player.getAudioTrack(),g.CP(a.Y)),c;
b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?c=W3(a,a.N):b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&U3(a)?c=V3(a):lhb(a)||a.N||mhb(a)?c=W3(a,a.N):U3(a)&&(c=V3(a));if(a.D||a.Ca){var d=g.WX(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.dh("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.UP(f));h.setAttribute("srclang",g.WP(f));h.setAttribute("id",f.toString());a.Ca||h.setAttribute("src",a.j.Fx(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.De();c.IE(b);c=
c.Ib();a.Lb&&a.oa.T(c.textTracks,"change",a.eda)}else!a.B&&c&&Y3(a,c),a.player.zd("onCaptionsTrackListChanged"),a.player.sf("onApiChange")},qhb=function(a,b){var c=a.J.De().Ib().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?e.mode!=="showing"&&(e.mode="showing"):e.mode==="showing"&&(e.mode="disabled"))}},Y3=function(a,b,c){a.loaded&&a.unload();
c!=null&&(a.N=c,a.N&&(g.CP(a.Y)?Z3(a,!!b):$3(a,!!b)));a.Y.L("html5_report_caption_format_change")&&rhb(a,a.B,b,a.N,!1);a.B=b;U3(a)&&(b=V3(a),a.Y.L("html5_report_caption_format_change")&&rhb(a,a.B,b,a.N,!0),a.B=b);var d;shb(a,(d=a.B)!=null?d:void 0);a.load()},uhb=function(a,b){if(b instanceof A3){var c=a.Aa[b.id];
c&&c.B!==b&&(c.dispose(),delete a.Aa[b.id],c=null);c||(c=thb(a,b))&&(a.Aa[b.id]=c)}else c=b.windowId,a.Ua[c]||(a.Ua[c]=[]),a.Ua[c].push(b)},thb=function(a,b){var c=vhb(a);
if(!c)return null;var d=a.B?g.WP(a.B):null;d&&g.$ab.test(d)&&(b.params.Ti=1);var e=a.rb.getPlayerSize();d=e.height*a.qa.height;e=e.width*a.qa.width;a.Y.playerStyle!=="google-live"||a.C.isDefault||Object.assign(b.params,a.C);switch(b.params.JB!=null?b.params.JB:b.j.length>1?1:0){case 1:return new L3(b,a.C,a.G,c.width,c.height,e,d,a.Y.experiments,a.MN.bind(a),a.J);case 2:return new Q3(b,a.C,a.G,c.width,c.height,e,d,a.Y.experiments,a.MN.bind(a),a.J);default:return new p3(b,a.C,a.G,c.width,c.height,e,
d,a.Y.experiments,a.MN.bind(a),a.J)}},jhb=function(a,b,c){c=c===void 0?!1:c;
var d=a4.Qe;a.C={};Object.assign(a.C,a4);a.C.Qe={};Object.assign(a.C.Qe,d);a.G={Qe:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;G3.test(f);e.Qe.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;G3.test(f);e.Qe.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||a4.windowColor;G3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;f==null&&(f=d.backgroundOpacity);e.Qe.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
f==null&&(f=d.fontSizeIncrement);e.Qe.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;e==null&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Qe;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;f==null&&(f=d.textOpacity);e.Qe.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;f==null&&(f=a4.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;f==null&&(f=d.charEdgeStyle);e.Qe.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;f==null&&(f=d.fontFamily);e.Qe.fontFamily=f;a.loaded&&a.XU();c&&g.Ms("yt-player-caption-display-settings",b,2592E3)},xhb=function(a,b,c){b&&!a.W?(b=Pgb({Ti:0,
lang:"en-GB"}),a.W=[b,new y3(b.start,b.end-b.start,0,b.id,c!=null?c:"Captions look like this")],a.player.nf(a.W)):!b&&a.W&&(whb(a,a.W),a.W=null)},whb=function(a,b){a.player.pp(b);
b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.Xb(a.Fa,c.value);m3(a.Ja)},shb=function(a,b){a.Y.L("html5_modify_caption_vss_logging")&&(a.videoData.mE=b)},vhb=function(a){var b=a.rb.getVideoContentRect(!0).height,c=a.rb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.qa.height;c*=a.qa.width;return{width:c,height:b}},$3=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},Z3=function(a,b){a.J.isInline()||g.Ms("yt-player-sticky-caption",b,2592E3)},khb=function(a){if(!a.J.isInline())return g.Ns("yt-player-sticky-caption")},ihb=function(a){var b,c=!((b=a.J.De())==null||!b.sI());
return a.Ta&&c&&!a.Va},ohb=function(a){return a.Y.L("web_deprecate_always_includes_asr_setting")&&g.CP(a.Y)?!0:!!g.Us(g.Ts(),66)},rhb=function(a,b,c,d,e){e?a.nj(c,!0,"g"):d?b?a.nj(c,!!c,"m"):c&&a.nj(c,!0,"m"):!b&&c&&a.nj(c,!0,"s")};
g.YX.prototype.qT=g.ba(55,function(){return!1});
g.YX.prototype.Pu=g.ba(54,function(){});
g.ZX.prototype.Pu=g.ba(53,function(a,b,c){var d=this;this.Ia();b=this.Fx(a,b);this.ut();Cfb(this,b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.$X.prototype.Pu=g.ba(52,function(a,b,c){var d=this;this.Ia();b=this.Fx(a,b);this.ut();this.j=g.Er(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.GX.prototype.iA=g.ba(51,function(){for(var a=g.Wg(document,"track",void 0,this.j),b=0;b<a.length;b++)g.ih(a[b])});
g.c_.prototype.iA=g.ba(50,function(){this.mediaElement.iA()});
g.GX.prototype.tI=g.ba(49,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.c_.prototype.tI=g.ba(48,function(){return this.mediaElement.tI()});
g.GX.prototype.sI=g.ba(47,function(){return!!this.j.textTracks});
g.c_.prototype.sI=g.ba(46,function(){return this.mediaElement.sI()});
g.GX.prototype.IE=g.ba(45,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.c_.prototype.IE=g.ba(44,function(a){this.mediaElement.IE(a)});
g.GV.prototype.BI=g.ba(40,function(a,b,c){this.Xc.BI(a,b,c)});
g.l_.prototype.BI=g.ba(39,function(a,b,c){this.Ja.set(a,{Ut:b,Uz:c})});
g.GV.prototype.LF=g.ba(38,function(a){return this.Xc.LF(a)});
g.l_.prototype.LF=g.ba(37,function(a){var b=2;this.K.has(a)?b=0:g.M5a(this,a)&&(b=1);return b});
g.ET.prototype.j=g.ba(36,function(a){g.sOa.apply(null,[6,this.tag,a].concat(g.x(g.Ca.apply(1,arguments))))});
g.aS.prototype.Wk=g.ba(34,function(a,b){var c=g.SR(this.app);c&&c.Wk(a,b)});
g.YV.prototype.Wk=g.ba(33,function(a,b){a=[a,b];g.XV(this,g.oK(this.provider),"cfi",a)});
g.lW.prototype.Wk=g.ba(32,function(a,b){this.qoe&&this.qoe.Wk(a,b)});
g.MW.prototype.Wk=g.ba(31,function(a,b){this.Qb().Wk(a,b)});
g.aS.prototype.nj=g.ba(30,function(a,b,c){var d=g.SR(this.app);d&&d.nj(a,b,c)});
g.YV.prototype.nj=g.ba(29,function(a,b,c){b=[a,b,this.Sb,c];g.XV(this,g.oK(this.provider),"cfs",b);this.Sb=a});
g.lW.prototype.nj=g.ba(28,function(a,b,c){this.qoe&&this.qoe.nj(a,b,c)});
g.MW.prototype.nj=g.ba(27,function(a,b,c){this.Qb().nj(a,b,c)});
g.BV.prototype.ZF=g.ba(18,function(){return this.N});
g.J_.prototype.ZF=g.ba(17,function(){var a;return((a=g.SR(this))==null?void 0:a.MA())||null});
g.aS.prototype.MA=g.ba(16,function(){return this.app.ZF()});
g.MW.prototype.MA=g.ba(15,function(){var a;return((a=this.ra)==null?void 0:a.ZF())||null});
g.eM.prototype.IK=g.ba(1,function(a){return(a=this.zo(a))?a.j:0});
g.DN.prototype.IK=g.ba(0,function(){return 0});
var Ifb=/#(.)(.)(.)/,Hfb=/^#(?:[0-9a-f]{3}){1,2}$/i,Qfb={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",
la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",
mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",
naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",
or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",
ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",
shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",
sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",
tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",
xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
n3.prototype.contains=function(a){a=g.fc(this.segments,a);return a>=0||a<0&&(-a-1)%2===1};
n3.prototype.length=function(){return this.segments.length/2};
g.z(Nfb,g.O);g.k=Nfb.prototype;g.k.xa=function(){g.O.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.VB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Ac();var b=this.j;this.j=g.Qb(this.oa.Xr(a).gb);b!==this.j&&this.W&&this.W()};
g.k.reset=function(){this.D=new n3;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.F_=function(){this.Ia();var a;if(a=this.j!=null)a=this.j,a=a.j.Ft(a);if(a&&!this.C&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){a=this.j;a=a.j.SD(a);var b=a.gb[0],c;if((c=this.player.getVideoData())==null?0:c.enableServerStitchedDai)if(c=this.player.MA()){var d=b.j.info.id,e=b.Oa,f=a.gb[0].We;if(this.policy.La){if(c=c.LK(f,e,d,3))a.D=c}else if(d=c.DA(f,e,d,3))if(c=c.LF(e),c===0)d&&(a.j=new g.XL(d));else if(c===2){this.N.start();Ofb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.Jo(b.Oa)?(this.D.contains(a.gb[0].Oa)||Pfb(this,a),this.j=g.Qb(a.gb)):Ofb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.z(o3,g.YX);g.k=o3.prototype;g.k.Pu=function(a,b,c){var d=this;this.ut();b=Sfb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?Tfb(this,b,"386"):Tfb(this,b));if(b){var e=(b.index.IK(b.index.Bo())-b.index.getStartTime(b.index.Bo()))*1E3,f=new g.yRa(this.Y),h=function(){d.C&&d.C.reset();d.K=!0};
this.Y.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new Nfb(f,this.J,b,function(l,m){c(l,a,m,e)},this.N||g.aG(b.info),h)}};
g.k.qT=function(){var a=this.K;this.K=!1;return a};
g.k.xB=function(a){var b=this.N?[new g.TP({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.TP({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?Rfb(this,"386"):Rfb(this);b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.XX(this.B,c.value);a()};
g.k.ut=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Fx=function(){return""};
g.k.KH=function(){this.C&&(this.C.reset(),this.J.jf("captions"))};
var G3=/^#(?:[0-9a-f]{3}){1,2}$/i;var Wfb=["left","right","center","justify"];g.z(p3,g.S);g.k=p3.prototype;g.k.e5=function(a,b){this.Va=a;this.ib=b;var c=g.Cm(this.element,this.element.parentElement);this.kb=a-c.x;this.rb=b-c.y};
g.k.d5=function(a,b){if(a!==this.Va||b!==this.ib){g.lp(this.element,"ytp-dragging")||g.mp(this.element,"ytp-dragging");var c=g.Em(this.element);a=a-this.kb-.02*this.playerWidth;var d=b-this.rb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.qg(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.qg(f,0,2));b=e+f*3;a=(a+e/2*c.width)/this.maxWidth;a=g.qg(a,0,1)*100;c=(d+f/2*c.height)/this.maxHeight;c=g.qg(c,0,1)*100;this.B.params.Lm=b;this.B.params.yp=c;this.B.params.Jk=
a;this.B.params.isDefault=!1;this.j.Lm=b;this.j.yp=c;this.j.Jk=a;this.j.isDefault=!1;this.qa.Lm=b;this.qa.yp=c;this.qa.Jk=a;this.qa.isDefault=!1;this.j2()}};
g.k.c5=function(){g.op(this.element,"ytp-dragging")};
g.k.j2=function(){this.OC(this.K)};
g.k.getType=function(){return this.type};
g.k.OC=function(a){var b=this.Ab?0:Math.min(this.RY(),this.maxWidth),c=this.QY(),d=this.Ab;if(d){var e=getComputedStyle(this.D.parentNode);e=q3(e.borderLeftWidth)+q3(e.borderRightWidth)+q3(e.paddingLeft)+q3(e.paddingRight)}else e=0;var f=e;e="";this.B.params.Ti===3&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.sm(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.JO(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=this.j.Jk*.96+2;h=this.j.Lm;switch(h){case 0:case 3:case 6:(d=this.j.Qe.fontSizeIncrement)&&d>0&&this.j.Ti!==2&&this.j.Ti!==3&&(l=Math.max(l/(1+d*2),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=this.j.yp*.96+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.sm(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],typeof e.text==="string"&&(d+=e.text.split("\n").length-1,e.append||b===0||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.JO=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Fa||this.K.length>b)b=0,this.Fa=!1,this.K=[],this.N=this.La=this.Ja=null,g.gh(this.D);for(;b<a.length;b++)agb(this,a[b])};
g.k.RY=function(){return 0};
g.k.QY=function(){return 0};
g.k.toString=function(){return g.S.prototype.toString.call(this)};cgb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
cgb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var vgb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];r3.prototype.set=function(a){this.type=a};
r3.prototype.get=function(){return this.type};
s3.prototype.clear=function(){this.state=0};
s3.prototype.update=function(){this.state=this.state===2?1:0};
s3.prototype.xe=function(){return this.state!==0};
s3.prototype.matches=function(a,b){return this.xe()&&a===this.Ww&&b===this.Mt};
Agb.prototype.reset=function(){this.timestamp=this.j=0};
t3.prototype.updateTime=function(a){for(var b=1;b<=15;++b)for(var c=1;c<=32;++c)this.B[b][c].timestamp=a};
t3.prototype.debugString=function(){for(var a="\n",b=1;b<=15;++b){for(var c=1;c<=32;++c){var d=this.B[b][c];a=d.j===0?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
t3.prototype.reset=function(a){for(var b=0;b<=15;b++)for(var c=0;c<=32;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var Bgb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Cgb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Dgb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Egb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Igb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
bgb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};Mgb.prototype.D=function(){};g.z(y3,g.nE);y3.prototype.toString=function(){return g.nE.prototype.toString.call(this)};g.z(z3,g.O);z3.prototype.fp=function(){return[]};
z3.prototype.reset=function(){};g.z(A3,g.nE);A3.prototype.toString=function(){return g.nE.prototype.toString.call(this)};
var B3=0;g.z(C3,z3);C3.prototype.reset=function(){this.K={};this.B=this.j=null;this.G=!0};
C3.prototype.fp=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.w(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,c.nodeType===1)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.w(d),a=d.next();!a.done;a=d.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=E3(a,"b");
l!=null&&(h.bold=l);l=E3(a,"i");l!=null&&(h.italic=l);l=E3(a,"u");l!=null&&(h.underline=l);l=F3(a,"et");l!=null&&(h.charEdgeStyle=l);l=F3(a,"of");l!=null&&(h.offset=l);l=H3(a,"bc");l!=null&&(h.background=l);l=H3(a,"ec");l!=null&&(h.aP=l);l=H3(a,"fc");l!=null&&(h.color=l);l=F3(a,"fs");l!=null&&l!==0&&(h.fontFamily=l);l=D3(a,"sz");l!==void 0&&(h.fontSizeIncrement=l/100-1);l=D3(a,"bo");l!==void 0&&(h.backgroundOpacity=l/255);l=D3(a,"fo");l!==void 0&&(h.textOpacity=l/255);l=F3(a,"rb");l!=null&&l!==10&&
l!==0&&(h.gg=l>10?l-1:l);a=F3(a,"hg");a!=null&&(h.LZ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=Qgb(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=Rgb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.w(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "w":this.j=Sgb(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!E3(m,"a");l=(D3(m,"t")||0)+l;var n=D3(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&this.B.text==="\n"&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=m.getAttribute("d")!=null);for(m=0;m<r.length;m++){var t=r[m],u=void 0;m>0&&(h=!0);var y=void 0;t.nodeType===1&&(y=t);if(y&&y.tagName==="s"){if((t=(t=y.getAttribute("p"))?this.pens[t]:null)&&t.gg&&(t.gg===1?(t=r.slice(m,
m+4),t.length===4&&(u=Ogb(l,n,f,h,p,t,this.pens),m+=3)):u=Ogb(l,n,f,h,p,[y],this.pens)),!u){var A=y;u=l;y=n;t=f;var C=h,G=p,H=A.textContent?A.textContent:"",M=A.getAttribute("p");M=M?this.pens[M]:null;A=D3(A,"t")||0;u=new y3(u+A,y-A,G,t,H,C,M)}}else u=new y3(l,n,p,f,t.textContent||"",h,q);c.push(u);this.B=u}if(c.length>0)for(c[0].windowId===this.D&&(this.j=Sgb(this,a,b,!0),d.push(this.j)),a=g.w(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var yhb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.z(I3,z3);I3.prototype.reset=function(){this.B.clear()};
I3.prototype.fp=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.w(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;h!=null&&(f.offset=h);e.szPenSize!==void 0&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;h!=null&&(f.charEdgeStyle=h);e.ecEdgeColor!==void 0&&(f.aP=J3(e.ecEdgeColor));h=e.fsFontStyle;h!=null&&h!==0&&(f.fontFamily=
h);e.fcForeColor!==void 0&&(f.color=J3(e.fcForeColor));e.foForeAlpha!==void 0&&(f.textOpacity=e.foForeAlpha/255);e.bcBackColor!==void 0&&(f.background=J3(e.bcBackColor));e.boBackAlpha!==void 0&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&h!==10&&(f.gg=h>10?h-1:h,f.vp=yhb.get(f.gg));e.hgHorizGroup&&(f.LZ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.w(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),e.mhModeHint!==void 0&&(f.JB=e.mhModeHint),e.juJustifCode!==void 0&&(f.textAlign=e.juJustifCode),e.pdPrintDir!==void 0&&(f.Ti=e.pdPrintDir),e.sdScrollDir!==void 0&&(f.KU=e.sdScrollDir),e.wfcWinFillColor!==void 0&&(f.windowColor=J3(e.wfcWinFillColor)),e.wfoWinFillAlpha!==void 0&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.w(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),e.ahHorPos!==
void 0&&(f.Jk=e.ahHorPos),e.apPoint!==void 0&&(f.Lm=e.apPoint),e.avVerPos!==void 0&&(f.yp=e.avVerPos),e.ccCols!==void 0&&(f.Pt=e.ccCols),e.rcRows!==void 0&&(f.Qs=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.w(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=Tgb(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+B3++,d=Tgb(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;f===0&&(f=5E3);
l=this.B.get(h);var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],u=t.utf8;if(u){var y=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if((l.params.JB!=null?l.params.JB:l.j.length>1?1:0)===2&&n&&u==="\n")continue;t=null;var C=[],G;if(G=A&&A.gg===1){G=q;var H=m;if(H+3>=G.length||!G[H+1].pPenId||!G[H+2].pPenId||!G[H+3].pPenId)G=!1;else{var M=G[H+1].pPenId;(M=this.j.get(M))&&M.gg&&M.gg===2?(M=G[H+2].pPenId,M=this.j.get(M),!M||!M.gg||
M.gg<3?G=!1:(M=G[H+3].pPenId,G=(M=this.j.get(M))&&M.gg&&M.gg===2?!0:!1)):G=!1}}if(G)y=q[m+1].utf8,t=q[m+3].utf8,G=q[m+2].utf8,H=this.j.get(q[m+2].pPenId),u=Ngb(u,y,G,t,H),t=new y3(e,f,p,h,u,n,A),m+=3;else{if(u.indexOf("<")>-1){var N=void 0;C=A;G=r;H=e;M=f;var X=y,V=p,ea=n,oa=[],Y=g.b1("<html>"+u+"</html>");if(!Y.getElementsByTagName("parsererror").length&&((N=Y.firstChild)==null?0:N.childNodes.length))for(N=g.w(Y.firstChild.childNodes),Y=N.next();!Y.done;Y=N.next()){Y=Y.value;var R=void 0,T=void 0,
v=(T=(R=Y.textContent)==null?void 0:R.replace(/\n/g,""))!=null?T:"";if(Y.nodeType!==3||v&&v.match(/^ *$/)==null){R={};Object.assign(R,C||G);T=void 0;switch((T=Y)==null?void 0:T.tagName){case "b":R.bold=!0;break;case "i":R.italic=!0;break;case "u":R.underline=!0}oa.push(new y3(H+X,M-X,V,l.id,v,ea,R))}}C=oa}C.length||(C=[new y3(e+y,f-y,p,l.id,u,n,A||r)])}if(C.length)for(n=g.w(C),A=n.next();!A.done;A=n.next())A=A.value,d.push(A),l.j.push(A);else t&&(d.push(t),l.j.push(t))}n=!0}}}b=a}else b=[];return b};g.z(K3,g.YX);K3.prototype.Pu=function(a,b,c){Gfb(this.videoData.videoId,a.vssId,c)};
K3.prototype.xB=function(a){if(this.audioTrack)for(var b=g.w(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.XX(this.B,c.value);a()};g.z(L3,p3);L3.prototype.JO=function(a){var b=this.B.j;p3.prototype.JO.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,zhb);var e=c.j;var f=d}agb(this,c,d)}};
var zhb={u$:!0};g.z(M3,Mgb);M3.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+B3++;c=c/1E3-this.K;d=d/1E3-this.K;a=new A3(c,d-c,5,f,{textAlign:0,Lm:0,Jk:b*2.5,yp:a*5.33});e=new y3(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.z(P3,z3);P3.prototype.fp=function(a){a=new M3(a,a.byteLength,this.B);if(Ugb(a)){for(;a.byteOffset<a.j.byteLength;)for(a.version===0?a.C=O3(a)*(1E3/45):a.version===1&&(a.C=O3(a)*4294967296+O3(a)),a.G=N3(a);a.G>0;a.G--){var b=N3(a),c=N3(a),d=N3(a);b&4&&(b&3)===this.track&&(this.track===0||this.track===1)&&(b=this.j,b.j.push({time:a.C,type:this.track,OX:c,PX:d,order:b.j.length}))}zgb(this.j,a);return a.B}return[]};
P3.prototype.reset=function(){this.j.clear()};g.z(Q3,p3);g.k=Q3.prototype;g.k.j2=function(){g.gp(this.Ta)};
g.k.wca=function(){g.op(this.element,"ytp-rollup-mode");this.OC(this.Sb,!0)};
g.k.QY=function(){return this.C?this.oa:this.W};
g.k.RY=function(){return this.C?this.W:this.oa};
g.k.OC=function(a,b){this.Sb=a;if(this.B.params.Qs){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;c>0&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Gb=this.oa;this.W=this.oa=0;p3.prototype.OC.call(this,a);Ygb(this,b)}p3.prototype.OC.call(this,a)};g.z(R3,z3);
R3.prototype.fp=function(a,b){var c=[];a=a.split(Ahb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(e!==""&&!Bhb.test(e)){var h=Chb.exec(e);if(h&&h.length>=4){var l=$gb(h[1]),m=$gb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.w(n);for(var u=n.next();!u.done;u=n.next())if(u=u.value.split(":"),u.length===2){var y=u[1];switch(u[0]){case "line":u=y.split(",");u[0].endsWith("%")&&(p=u[0],h.yp=Number.parseInt(p,10),u.length===2&&(q=u[1].trim()));break;case "position":u=
y.split(",");r=u[0];h.Jk=Number.parseInt(r,10);u.length===2&&(t=u[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Jk=0;break;case 1:h.Jk=100;break;case 2:h.Jk=50}if(h.textAlign!=null){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=p<0||p>8?7:p;h.Lm=q}e=e.substring(Chb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(h.indexOf("<")<0&&h.indexOf("&")<0)f=ahb(l,m,5,t),m=new y3(l,m,5,f.id,h,!1,g.Ig(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(Dhb),q.length===1?(h=5,t=ahb(l,m,h,t)):(p=h=6,t=Object.assign({Pt:32},t),t=new A3(l,m,p,"_"+B3++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],r%2===0?(u=g.b1("<html>"+n+"</html>"),u.getElementsByTagName("parsererror").length?
(y=u.createElement("span"),y.appendChild(u.createTextNode(n))):y=u.firstChild,Zgb(this,p,m-(p-l),h,t,r>0,y,e,c)):p=$gb(n)+f}Chb.lastIndex=0}}return c};
var Bhb=/^NOTE/,Ahb=/(?:\r\n|\r|\n){2,}/,Chb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Dhb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.d_.fL(R3,{fp:"wvppt"});g.z(S3,g.O);
S3.prototype.fp=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a||this.Y.L("html5_use_subfragcaps_parser_for_all_live")){a:{var e=d,f=dhb(this,a,c),h=[];try{for(var l=g.w(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.EU;h=typeof p!=="string"?h.concat(ehb(this,b,p,q,e)):p.substring(0,6)==="WEBVTT"?h.concat(fhb(this,p,q)):h.concat(hhb(this,b,p,q))}var r=h;break a}catch(u){this.logger.j(187101178,"SS caps parsing failure fallback: "+u.message+". ");this.clear();r=null;break a}r=void 0}if(r!==
null&&r.length!==0)return r;if(this.Y.L("html5_disable_subfragcaps_fallback"))return[];r===null?(r=this.logger,g.vOa(r.tag,5,"SS caps fallback due to parse failure.",r.B)):this.logger.info("SS caps fallback due to no data received.")}if(a=bhb(a))try{var t=typeof a!=="string"?ehb(this,b,a,c,d):a.substring(0,6)==="WEBVTT"?fhb(this,a,c):hhb(this,b,a,c)}catch(u){this.clear(),t=[]}else t=[];return t};
S3.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
S3.prototype.reset=function(){this.j&&this.j.reset()};
S3.prototype.xa=function(){g.O.prototype.xa.call(this);this.clear()};var a4={windowColor:"#080808",windowOpacity:0,textAlign:2,Lm:7,Jk:50,yp:100,isDefault:!0,Qe:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.z(T3,g.VX);g.k=T3.prototype;g.k.xa=function(){if(this.D||this.Ca){var a=this.J.De();a&&!a.Ia()&&a.iA()}else xhb(this,!1);g.VX.prototype.xa.call(this)};
g.k.qU=function(){return this.Y.L("html5_honor_caption_availabilities_in_audio_track")&&!this.Va};
g.k.Gv=function(){if(this.Ta)return this.D||this.Ca;var a=this.getAudioTrack();if(this.qU()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=Dfb(a,g.CP(this.Y));return a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?U3(this):lhb(this)||U3(this)?!0:mhb(this)};
g.k.load=function(){var a=this;g.VX.prototype.load.call(this);this.Z=this.getAudioTrack();this.j?this.B&&(this.Wa.clear(),this.D?qhb(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.Pu(this.B,"json3",function(b,c,d,e){if(b){var f;shb(a,(f=a.B)!=null?f:void 0);a.j.qT()&&(a.Fa=[],a.J.jf("captions"),m3(a.Ja),a.Wa.reset());if(a.videoData.xd){var h;d=((h=d)!=null?h:0)+a.videoData.xd}b=a.Wa.fp(b,c,d,e);if(a.ib)for(c=g.w(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.fm=a.videoData.xd;c=!a.Y.L("html5_keep_caption_data_after_seek")&&a.Va;a.player.nf(b,void 0,c);!a.N||a.Ca||X3(a)||!a.Y.Jn||g.LD(a.Y)||g.oP(a.Y)||g.Wy(a.Y)||a.Y.Ja==="shortspage"||a.player.isInline()||(g.hp(a.La),b=Pgb({Lm:0,Jk:5,yp:5,Qs:2,textAlign:0,Ti:0,lang:"en-GB"}),a.Na=[b],c=["Click "," for settings"],a.kb||(e=new g.ux(g.Nx()),g.P(a,e),a.kb=e.element),e=b.end-b.start,(f=g.UP(a.B))&&a.Na.push(new y3(b.start,e,0,b.id,f)),a.Na.push(new y3(b.start,e,0,b.id,c[0]),new y3(b.start,e,0,b.id,a.kb,!0),
new y3(b.start,e,0,b.id,c[1],!0)),a.player.nf(a.Na),g.fp(a.La));!a.N||a.Ca||X3(a)||(g.CP(a.Y)?Z3(a,!0):$3(a,!0),a.Z&&(a.Z.D=a.B),a.player.Cp());a.N=!1}}),this.D||this.Ca||X3(this)||this.player.zd("captionschanged",g.VP(this.B))):(this.j=nhb(this),g.P(this,this.j),this.j.xB(function(){phb(a)}))};
g.k.unload=function(){this.D&&this.B?qhb(this,!1):(this.La&&g.hp(this.La),this.player.jf("captions"),this.Fa=[],this.j&&this.j.ut(),this.Wa.clear(),this.W&&this.player.nf(this.W),this.XU());g.VX.prototype.unload.call(this);this.player.Cp();this.player.zd("captionschanged",{})};
g.k.create=function(){this.Gv()&&this.load();var a;a:{var b,c,d;if(this.Y.L("web_player_nitrate_promo_tooltip")&&((b=this.videoData.getPlayerResponse())==null?0:(c=b.captions)==null?0:(d=c.playerCaptionsTracklistRenderer)==null?0:d.enableTouchCaptionsNitrate)){var e,f;if(b=(a=this.videoData.getPlayerResponse())==null?void 0:(e=a.captions)==null?void 0:(f=e.playerCaptionsTracklistRenderer)==null?void 0:f.captionTracks)for(a=g.w(b),e=a.next();!e.done;e=a.next())if(e=e.value,e.kind==="asr"&&e.languageCode===
"en"){a=!0;break a}}a=!1}a&&this.J.publish("showpromotooltip",this.K.element)};
g.k.eda=function(){for(var a=this.J.De().Ib().textTracks,b=null,c=0;c<a.length;c++)if(a[c].mode==="showing")a:{b=g.WX(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&Y3(this,b,!0)};
g.k.Jfa=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Fa.push(a);m3(this.Ja)};
g.k.onCueRangeExit=function(a){g.Xb(this.Fa,a);this.j instanceof o3&&this.j.N&&this.player.pp([a]);m3(this.Ja)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.eea=function(){whb(this,this.Na);this.Na=null};
g.k.WU=function(){var a=this;if(!this.Ab||!this.D){this.Ja.stop();g.Fea(this.Ua);this.Fa.sort(g.oE);var b=this.Fa;if(this.W){var c=g.on(b,function(f){return this.W.indexOf(f)===-1},this);
c.length&&(b=c)}b=g.w(b);for(c=b.next();!c.done;c=b.next())uhb(this,c.value);b=g.w(Object.entries(this.Aa));var d=b.next();for(c={};!d.done;c={aB:void 0,Wp:void 0},d=b.next()){var e=g.w(d.value);d=e.next().value;e=e.next().value;c.aB=d;c.Wp=e;this.Ua[c.aB]?(c.Wp.element.parentNode||(c.Wp instanceof Q3||c.Wp instanceof L3||g.Bg(this.Aa,function(f){return function(h,l){l!==f.aB&&h.B.params.Lm===f.Wp.B.params.Lm&&h.B.params.Jk===f.Wp.B.params.Jk&&h.B.params.yp===f.Wp.B.params.yp&&(h.dispose(),delete a.Aa[l]);
return l===f.aB}}(c),this),this.K.element.appendChild(c.Wp.element)),c.Wp.OC(this.Ua[c.aB])):(c.Wp.dispose(),delete this.Aa[c.aB])}}};
g.k.lea=function(){jhb(this,{},!0);this.player.zd("captionssettingschanged")};
g.k.G9=function(){var a=a4.Qe;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:a4.windowColor,windowOpacity:a4.windowOpacity};var b=Lfb()||{};b.background!=null&&(a.background=b.background);b.backgroundOverride!=null&&(a.backgroundOverride=b.backgroundOverride);b.backgroundOpacity!=null&&(a.backgroundOpacity=
b.backgroundOpacity);b.backgroundOpacityOverride!=null&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);b.charEdgeStyle!=null&&(a.charEdgeStyle=b.charEdgeStyle);b.charEdgeStyleOverride!=null&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);b.color!=null&&(a.color=b.color);b.colorOverride!=null&&(a.colorOverride=b.colorOverride);b.fontFamily!=null&&(a.fontFamily=b.fontFamily);b.fontFamilyOverride!=null&&(a.fontFamilyOverride=b.fontFamilyOverride);b.fontSizeIncrement!=null&&(a.fontSizeIncrement=
b.fontSizeIncrement);b.fontSizeIncrementOverride!=null&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);b.fontStyle!=null&&(a.fontStyle=b.fontStyle);b.fontStyleOverride!=null&&(a.fontStyleOverride=b.fontStyleOverride);b.textOpacity!=null&&(a.textOpacity=b.textOpacity);b.textOpacityOverride!=null&&(a.textOpacityOverride=b.textOpacityOverride);b.windowColor!=null&&(a.windowColor=b.windowColor);b.windowColorOverride!=null&&(a.windowColorOverride=b.windowColorOverride);b.windowOpacity!=null&&
(a.windowOpacity=b.windowOpacity);b.windowOpacityOverride!=null&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.V3=function(a,b){var c={};Object.assign(c,Lfb());Object.assign(c,a);jhb(this,c,b);this.player.zd("captionssettingschanged")};
g.k.XU=function(){!this.D&&this.loaded&&(g.yg(this.Aa,function(a,b){a.dispose();delete this.Aa[b]},this),this.WU())};
g.k.gi=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.qg(b,-2,4);this.V3({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&Y3(this,this.B,!0);break;case "stickyLoading":b!==void 0&&this.Y.N&&(g.CP(this.Y)?Z3(this,!!b):$3(this,!!b));break;case "track":if(!this.j)return{};if(b){this.Y.L("html5_report_caption_format_intent")&&!g.Ig(b)&&this.Wk(b.vss_id,"m");if(this.D)break;if(!g.Sa(b))break;if(g.Ig(b)){Y3(this,null,!0);break}a=g.WX(this.j.B,!0);for(var d=0;d<a.length;d++){var e=
a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||(e.captionId||"")!==(b.captionId||"")||g.UP(e)!==b.displayName)||(c=b.translationLanguage?Efb(e,b.translationLanguage):e)}this.yN(b.position);!c||c===this.B&&this.loaded||(b=g.tL(),a=g.WP(c),b.length&&a===b[b.length-1]||(b.push(a),g.Ms("yt-player-caption-language-preferences",b)),g.CP(this.Y)&&!this.J.isInline()&&g.Ms("yt-player-caption-sticky-language",a,2592E3),Y3(this,c,!0))}else return this.loaded&&this.B&&!X3(this)?g.VP(this.B):
{};return"";case "tracklist":return this.j?g.Cl(g.WX(this.j.B,!(!b||!b.includeAsr)),function(f){return g.VP(f)}):[];
case "translationLanguages":return this.j?this.j.G.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||b===void 0||xhb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||xhb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.tL();case "defaultTranslationSourceTrackIndices":return this.j?this.j.Z:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.N&&a.push("stickyLoading");return a};
g.k.Yr=function(){var a=this.B;if(this.Y.L("html5_cue_ranges_based_caption_vss")&&!this.J.UK("captions"))return{};if(this.Y.L("html5_modify_caption_vss_logging")){var b;return(a=(b=this.videoData.mE)!=null?b:null)?{cc:g.oKa(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.WP(a)),{cc:b}):{}};
g.k.vfa=function(){this.isSubtitlesOn()?(g.CP(this.Y)?Z3(this,!1):$3(this,!1),shb(this),this.Y.L("html5_report_caption_format_change")?Y3(this,null,!0):(this.unload(),U3(this,!0)&&Y3(this,V3(this),!1))):this.w3()};
g.k.w3=function(){var a=X3(this)||!this.B?W3(this,!0):this.B;this.Y.L("html5_report_caption_format_intent")&&a&&this.Wk(a.vssId,"m");this.isSubtitlesOn()||Y3(this,X3(this)||!this.B?W3(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!X3(this)};
g.k.aH=function(){this.j&&this.j.aH()};
g.k.Raa=function(){var a=X3(this);U3(this,a)?Y3(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.qU()&&(this.N=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Gv()&&(a?Y3(this,W3(this),!1):this.load()))};
g.k.yN=function(a){a&&(this.qa={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=this.qa.top*100+"%",this.K.element.style.left=this.qa.left*100+"%",this.K.element.style.width=this.qa.width*100+"%",this.K.element.style.height=this.qa.height*100+"%",this.K.element.style.position="absolute",a=vhb(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){a==="newdata"&&(this.videoData=b,this.loaded&&this.unload(),this.N=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.zd("captionschanged",{})),this.Gv()&&this.load())};
g.k.getAudioTrack=function(){return this.ib&&this.player.getPresentingPlayerType()===2?this.videoData.bl:this.player.getAudioTrack()};
g.k.Fba=function(){var a=this.J.De();a&&!a.Ia()&&a.iA();this.J.isFullscreen()?(this.D=this.Ta=!0,this.loaded&&phb(this)):(this.Ta=this.Y.controlsType==="3",this.D=ihb(this));Y3(this,this.B)};
g.k.MN=function(){var a,b,c,d=(a=this.videoData.getPlayerResponse())==null?void 0:(b=a.captions)==null?void 0:(c=b.playerCaptionsTracklistRenderer)==null?void 0:c.openTranscriptCommand;d&&this.player.eb("innertubeCommand",d)};
g.k.nj=function(a,b,c){var d=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,e="";a&&(e=a.vssId,e=e.replace(d,""));var f="";a&&a.getId()&&(f=a.getId()||"",f=f.replace(d,""));a&&a.getXtags()&&(a=a.getXtags(),a=a.replace(d,""),f=f.concat(";"+a));this.J.nj(b?e:"",b?f:"",c)};
g.k.Wk=function(a,b){a=(a||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");this.J.Wk(a,b)};
g.k.KH=function(){this.j instanceof o3&&this.j.KH()};
g.d_.fL(T3,{WU:"smucd"});g.UX("captions",T3);})(_yt_player);
