var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(n){function x(a){try{return JSON.parse(a)}catch(b){return JANRAIN.SSO.warn("json array did not parse: "+a),[]}}function A(a){var b=document.createElement("a");b.href=a;return b.pathname.replace(/\//g,"_")}function B(a,b){JANRAIN.SSO.debug_log("checkVisited: ",a);var c={found:!1,isLoggedIn:!1};if(null==a||"undefined"===typeof a)return c;for(idx=0;idx<a.length;idx++){var f=a[idx];currentReceiverKey=v(f.xdReceiverURI);if("undefined"!==typeof currentReceiverKey&&currentReceiverKey===b){JANRAIN.SSO.debug_log("checkVisited found "+
b+" on "+f.domain);c.domain=f.domain;c.found=!0;JANRAIN.SSO.debug_log("checkVisited: is "+(f.isLoggedIn?"":"not ")+"logged in");c.isLoggedIn=f.isLoggedIn;break}}return c}function C(){var a=q(window.location.href);if(a.queryKey.token_url&&(a=q(decodeURIComponent(a.queryKey.token_url)),a.queryKey.xd_receiver))return decodeURIComponent(a.queryKey.xd_receiver)}function t(a){cName="";pCOOKIES=[];pCOOKIES=document.cookie.split("; ");for(bb=0;bb<pCOOKIES.length;bb++)NmeVal=[],NmeVal=pCOOKIES[bb].split("\x3d"),
NmeVal[0]==a&&(cName=unescape(NmeVal[1]));1<cName.length&&('"'===cName[0]&&(cName=cName.substr(1,cName.length)),'"'===cName[cName.length-1]&&(cName=cName.substr(0,cName.length-1)));return cName.replace(/\\"/g,'"')}function z(a,b,c,f,p,w){a=a+"\x3d"+escape(b);c&&(c=(new Date((new Date).getTime()+864E5*c)).toGMTString(),a+=";expires\x3d"+c);f&&(a+=";path\x3d"+f);p&&(a+=";domain\x3d"+p);w&&(a+="secure; ");document.cookie=a}function v(a){a=q(a);return a.host+a.path}function q(a){var b=q.options;a=b.parser[b.strictMode?
"strict":"loose"].exec(a);for(var c={},f=14;f--;)c[b.key[f]]=a[f]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(a,f,e){f&&(c[b.q.name][f]=e)});return c}function h(a,b){this.origin="https://"+q(a).host;this.path=b;this._iframe=null;this._iframeReady=!1;this._queue=[];this._requests={};this._messageId=0}if(!("undefined"!==typeof n.JANRAIN&&n.JANRAIN.SSO)){JANRAIN={SSO:{}};JANRAIN.SSO.version="3.2.3";JANRAIN.SSO.CAPTURE={};JANRAIN.SSO.ENGAGE={};var E=!1;window.localStorage&&(E=window.localStorage.getItem("janrainSsoDebugEnabled"));
var l,e,r,s,u,k,g,D,F,m,G,y;JANRAIN.SSO.debug_log=function(a,b){E&&(b&&(window.JSON&&window.JSON.stringify&&(b=JSON.stringify(b)),a+=": "+b),d=new Date,a="SSO DEBUG ("+d.toGMTString()+"): "+a,window.console&&window.console.debug?console.debug(a):window.console&&window.console.log&&console.log(a))};JANRAIN.SSO.log=function(a,b){window.console&&window.console.log&&(b&&(window.JSON&&window.JSON.stringify&&(b=JSON.stringify(b)),a+=": "+b),d=new Date,console.log("SSO ("+d.toGMTString()+"): "+a))};JANRAIN.SSO.warn=
function(a){window.console&&window.console.warn&&console.warn("SSO WARNING: "+a)};JANRAIN.SSO.error=function(a){window.console&&window.console.error&&console.error("SSO ERROR: "+a)};JANRAIN.SSO.useCookiesOnly=function(){"undefined"===typeof G&&(G=navigator&&navigator.userAgent&&-1<navigator.userAgent.search("__use_cookies__")?!0:!1);return G};JANRAIN.SSO.remoteStorage=function(a){a=a||e;m||(m=new h(a,"/static/server.html"));return m};JANRAIN.SSO.getSsoServer=function(){return e};JANRAIN.SSO._debugDump=
function(){window.console&&window.console.log&&(console.log("version: "+JANRAIN.SSO.version),console.log("use cookies only: "+JANRAIN.SSO.useCookiesOnly()),console.log("sso server: "+JANRAIN.SSO.getSsoServer()),rs=JANRAIN.SSO.remoteStorage(),rs.getValue(janrain.settings.segment,"get",function(a,b){console.log("session id: "+b.session_id);visitedArray=x(b.visited);if(null!=visitedArray)for(idx=0;idx<visitedArray.length;idx++)domain=visitedArray[idx].domain,xdReceiverURI=visitedArray[idx].xdReceiverURI,
isLoggedIn=visitedArray[idx].isLoggedIn,logoutURI=visitedArray[idx].logoutURI,console.log("visited "+(idx+1)+": "),console.log("        "+domain),console.log("        "+xdReceiverURI),console.log("        "+isLoggedIn),console.log("        "+logoutURI)}))};JANRAIN.SSO.CAPTURE.logout=function(a,b){JANRAIN.SSO.logout(a,b)};JANRAIN.SSO.ENGAGE.logout=function(a,b){JANRAIN.SSO.logout(a,b)};JANRAIN.SSO.CAPTURE.refresh=function(a){JANRAIN.SSO.refresh(a)};JANRAIN.SSO.ENGAGE.refresh=function(a){JANRAIN.SSO.refresh(a)};
JANRAIN.SSO.CAPTURE.refresh_token=function(a){if("undefined"===typeof e||"undefined"===typeof r)JANRAIN.SSO.error("check_login must be called before calling refresh_token");else if(window.localStorage&&!JANRAIN.SSO.useCookiesOnly()){m||(m=new h(sso_server_use,"/static/server.html"));JANRAIN.SSO.log("finding a segment to request new capture token on");JANRAIN.SSO.debug_log("Segments to check: "+F);v(s);var b;F.some(function(a){m.getValue(a,"get",function(c,f){b||(JANRAIN.SSO.log("checking segment: "+
a),!f.session_id||1>f.session_id.length?JANRAIN.SSO.log("no session found"):(JANRAIN.SSO.log("found a session; will request new token"),b=f.session_id))})});setTimeout(function(){if(b){var c=document.createElement("script");c.src=e+"/capture/v1/refresh_token?v\x3d"+(new Date).getTime()+"\x26redirect_uri\x3d"+encodeURIComponent(r)+"\x26callback\x3d"+encodeURIComponent(a)+"\x26client_id\x3d"+encodeURIComponent(k)+"\x26xdreceiver_uri\x3d"+encodeURIComponent(s)+"\x26logout_uri\x3d"+encodeURIComponent(u)+
"\x26session_id\x3d"+encodeURIComponent(b)+"\x26origin\x3d"+encodeURIComponent(n.document.location.href);c.type="text/javascript";var f=document.getElementsByTagName("script")[0];f.parentNode.insertBefore(c,f)}else JANRAIN.SSO.error("no session found; cannot request new capture token")},1E3)}else{var c=document.createElement("script");c.src=e+"/capture/v1/refresh_token?v\x3d"+(new Date).getTime()+"\x26redirect_uri\x3d"+encodeURIComponent(r)+"\x26callback\x3d"+encodeURIComponent(a)+"\x26client_id\x3d"+
encodeURIComponent(k)+"\x26xdreceiver_uri\x3d"+encodeURIComponent(s)+"\x26logout_uri\x3d"+encodeURIComponent(u)+"\x26origin\x3d"+encodeURIComponent(n.document.location.href);c.type="text/javascript";var f=document.getElementsByTagName("script")[0];f.parentNode.insertBefore(c,f)}};JANRAIN.SSO.CAPTURE.set_login=function(a){if("undefined"===typeof e||"undefined"===typeof r)JANRAIN.SSO.error("check_login must be called before calling set_login");else{var b=document.createElement("script");b.src=e+"/capture/v1/set_login?v\x3d"+
(new Date).getTime()+"\x26redirect_uri\x3d"+encodeURIComponent(r)+"\x26code\x3d"+encodeURIComponent(a.code)+"\x26login_callback\x3d"+encodeURIComponent(a.login_callback)+"\x26transaction_id\x3d"+encodeURIComponent(a.transaction_id);b.type="text/javascript";a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)}};JANRAIN.SSO.CAPTURE.check_login=function(a){e=e||a.sso_server;r=r||a.redirect_uri;s=s||a.xd_receiver;u=u||a.logout_uri;k=k||a.client_id;g=g||a.response_type;y=!1;a.response_type=
a.response_type||"code";a.response_method=a.response_method||"redirect";a.refresh=a.refresh||!1;a.segment=void 0===a.segment?"":a.segment.replace(/ /g,"_");a.supported_segments_ary=[];void 0!==a.supported_segments&&(a.supported_segments_ary=a.supported_segments.split("-"));a.supported_segments_ary.push(a.segment);F=a.supported_segments_ary;void 0===a.logout_uri&&(a.logout_uri="");void 0===a.bp_uri&&(a.bp_uri="");if(window.localStorage&&!JANRAIN.SSO.useCookiesOnly())JANRAIN.SSO.check_login_dispatch(a,
JANRAIN.SSO.CAPTURE.handleSegmentCheck);else{var b="janrain_sso_checked_"+A(a.xd_receiver);if(-1===n.document.cookie.search(RegExp(b)))b=document.createElement("script"),b.src=e+"/capture/v1/sso_check.js?v\x3d"+(new Date).getTime()+"\x26xd_receiver\x3d"+encodeURIComponent(s)+"\x26origin\x3d"+encodeURIComponent(n.document.location.href)+"\x26logout_uri\x3d"+encodeURIComponent(u)+"\x26redirect_uri\x3d"+encodeURIComponent(r)+"\x26client_id\x3d"+encodeURIComponent(k)+"\x26bp_channel\x3d"+encodeURIComponent(a.bp_channel)+
"\x26segment\x3d"+encodeURIComponent(a.segment)+"\x26response_type\x3d"+encodeURIComponent(g)+"\x26response_method\x3d"+encodeURIComponent(a.response_method)+"\x26widget_parameters\x3d"+encodeURIComponent(a.widget_parameters)+"\x26nologin_callback\x3d"+encodeURIComponent(a.nologin_callback)+"\x26transaction_id\x3d"+encodeURIComponent(a.transaction_id)+"\x26refresh\x3d"+a.refresh,b.type="text/javascript",a=document.getElementsByTagName("script")[0],a.parentNode.insertBefore(b,a);else if("undefined"!==
typeof janrain&&janrain.capture&&janrain.capture.ui&&"function"===typeof janrain.capture.ui[a.nologin_callback])janrain.capture.ui[a.nologin_callback]({transactionId:a.transaction_id,result:"already checked"})}};JANRAIN.SSO.CAPTURE.handleSegmentCheck=function(a,b,c,f){var p=[],w={found:!1},e=v(a.xd_receiver),g=q(a.xd_receiver).host;JANRAIN.SSO.log("checking segment "+c);if(!b.visited_expires||"session"===b.visited_expires)b.visited_expires="session","session"!==t("janrainSSO_session")&&(a.refresh=
!0,JANRAIN.SSO.log("visited tracker is session-based but no janrainSSO_session cookie found; will refresh even if marked as logged in"),z("janrainSSO_session","session",null,"/"));if(b.visited&&(p=x(b.visited),w=B(p,e),JANRAIN.SSO.debug_log("handleSegmentCheck visitedStatus",w),!0===w.found))if(!0===w.isLoggedIn)if(JANRAIN.SSO.log("already logged into: "+w.domain),a.refresh&&!y)JANRAIN.SSO.log("overriding with refresh");else{if("undefined"!==typeof janrain&&janrain.capture&&janrain.capture.ui&&"function"===
typeof janrain.capture.ui[a.nologin_callback])janrain.capture.ui[a.nologin_callback]({transactionId:a.transaction_id,result:"already checked"});return}else JANRAIN.SSO.log("found: "+w.domain+" but not logged in");if(!w.found){var h=q(a.xd_receiver);p.push({domain:h.host+h.path,xdReceiverURI:a.xd_receiver,isLoggedIn:!1,logoutURI:a.logout_uri});10<p.length&&p.splice(0,1)}!b.session_id||1>b.session_id.length?(JANRAIN.SSO.log("no session exists; not logging in"),f=function(){if("undefined"!==typeof janrain&&
janrain.capture&&janrain.capture.ui&&"function"===typeof janrain.capture.ui[a.nologin_callback])janrain.capture.ui[a.nologin_callback]({transactionId:a.transaction_id,result:"sso failed - no session exists"})},w.found?f():JANRAIN.SSO._setSession(b.session_id,JSON.stringify(p),b.visited_expires,c,g,f)):(!b.visited&&!y&&(a.refresh=!0,JANRAIN.SSO.log("session exists, but no visited list; forcing a refresh")),f&&!a.refresh||y?(JANRAIN.SSO.log("capture user already logged in to the site; marking as logged in on this segment, too"),
p.some(function(a,b){if(v(a.xdReceiverURI)===e)return p[b].isLoggedIn=!0}),JANRAIN.SSO._setSession(b.session_id,JSON.stringify(p),b.visited_expires,c,g)):(y=!0,JANRAIN.SSO.log("logging in capture user"),JANRAIN.SSO.CAPTURE._login(a,b.session_id,JSON.stringify(p),"JANRAIN.SSO.CAPTURE._loginCallback",c)))};JANRAIN.SSO.CAPTURE._login=function(a,b,c,f,p){if("undefined"===typeof e)JANRAIN.SSO.error("sso server is not defined");else{var w=document.createElement("script");w.src=e+"/capture/loginx?v\x3d"+
(new Date).getTime()+"\x26callback\x3d"+encodeURIComponent(f)+"\x26xd_receiver\x3d"+encodeURIComponent(s)+"\x26origin\x3d"+encodeURIComponent(n.document.location.href)+"\x26logout_uri\x3d"+encodeURIComponent(u)+"\x26redirect_uri\x3d"+encodeURIComponent(r)+"\x26client_id\x3d"+encodeURIComponent(k)+"\x26bp_channel\x3d"+encodeURIComponent(a.bp_channel)+"\x26segment\x3d"+encodeURIComponent(p)+"\x26response_type\x3d"+encodeURIComponent(a.response_type)+"\x26response_method\x3d"+encodeURIComponent(a.response_method)+
"\x26widget_parameters\x3d"+encodeURIComponent(a.widget_parameters)+"\x26transaction_id\x3d"+encodeURIComponent(a.transaction_id)+"\x26session_id\x3d"+encodeURIComponent(b)+"\x26visited\x3d"+encodeURIComponent(c);w.type="text/javascript";a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(w,a)}};JANRAIN.SSO.CAPTURE._loginCallback=function(a){if(!a||"fail"===a.stat)JANRAIN.SSO.error("login failed: "+a.msg);else{JANRAIN.SSO.log("callback from SSO server received");m||(m=new h(e,"/static/server.html"));
JANRAIN.SSO.log("updating SSO session");var b={session_id:decodeURIComponent(a.session_id),visited:decodeURIComponent(a.visited),visited_expires:a.visited_expires};m.setValue(a.segment,"set",b,function(b,f){a.capture_callback&&"jsonp"===a.response_method&&"undefined"!==typeof janrain&&janrain.capture&&janrain.capture.ui&&"function"===typeof a.capture_callback?a.capture_callback():a.redirect_uri&&0<a.redirect_uri.length&&(n.document.location.href=a.redirect_uri)})}};JANRAIN.SSO.ENGAGE.check_login=
function(a){e=e||a.sso_server;s=s||a.xd_receiver;u=u||a.logout_uri;l=a.token_uri;y=!1;a.segment=void 0===a.segment?"":a.segment.replace(/ /g,"_");a.supported_segments_ary=[];void 0!==a.supported_segments&&(a.supported_segments_ary=a.supported_segments.split("-"));a.supported_segments_ary.push(a.segment);void 0===a.logout_uri&&(a.logout_uri="");void 0===a.bp_uri&&(a.bp_uri="");if(void 0===a.xd_receiver)JANRAIN.SSO.error("configuration value xd_receiver undefined");else if(window.localStorage&&!JANRAIN.SSO.useCookiesOnly())JANRAIN.SSO.check_login_dispatch(a,
JANRAIN.SSO.ENGAGE.handleSegmentCheck);else{var b="janrain_sso_checked_"+A(a.xd_receiver);-1===n.document.cookie.search(RegExp(b))&&(b=document.createElement("script"),b.src=a.sso_server+"/session/sso_check.js?v\x3d"+(new Date).getTime()+"\x26xdcomm_uri\x3d"+encodeURIComponent(a.xd_receiver)+"\x26bp_channel\x3d"+encodeURIComponent(a.bp_channel)+"\x26segment\x3d"+encodeURIComponent(a.segment)+"\x26logout_uri\x3d"+encodeURIComponent(a.logout_uri),b.type="text/javascript",a=document.getElementsByTagName("script")[0],
a.parentNode.insertBefore(b,a))}};JANRAIN.SSO.ENGAGE.handleSegmentCheck=function(a,b,c,f){var p=[],e={found:!1},g=v(a.xd_receiver),h=q(a.xd_receiver).host;JANRAIN.SSO.log("checking segment "+c);if(!b.visited_expires||"session"===b.visited_expires)b.visited_expires="session","session"!==t("janrainSSO_session")&&(a.refresh=!0,JANRAIN.SSO.log("visited tracker is session-based but no janrainSSO_session cookie found; will refresh even if marked as logged in"),z("janrainSSO_session","session",null,"/"));
if(b.visited&&(p=x(b.visited),e=B(p,g),JANRAIN.SSO.debug_log("handleSegmentCheck visitedStatus",e),!0===e.found))if(!0===e.isLoggedIn)if(JANRAIN.SSO.log("already logged into: "+e.domain),a.refresh&&!y)JANRAIN.SSO.log("overriding with refresh");else return;else JANRAIN.SSO.log("found: "+e.domain+" but not logged in");if(!e.found){var l=q(a.xd_receiver);p.push({domain:l.host+l.path,xdReceiverURI:a.xd_receiver,isLoggedIn:!1,logoutURI:a.logout_uri});10<p.length&&p.splice(0,1)}!b.session_id||1>b.session_id.length?
(JANRAIN.SSO.log("no session exists; not logging in"),e.found||JANRAIN.SSO._setSession(b.session_id,JSON.stringify(p),b.visited_expires,c,h,function(){})):(!b.visited&&!y&&(a.refresh=!0,JANRAIN.SSO.log("session exists, but no visited list; forcing a refresh")),f&&!a.refresh||y?(JANRAIN.SSO.log("user already logged in to the site; marking as logged in on this segment, too"),p.some(function(a,b){if(v(a.xdReceiverURI)===g)return p[b].isLoggedIn=!0}),JANRAIN.SSO._setSession(b.session_id,JSON.stringify(p),
b.visited_expires,c,h)):(y=!0,JANRAIN.SSO.log("logging in user"),JANRAIN.SSO.ENGAGE._login({session_id:b.session_id,xd_receiver:a.xd_receiver,visited:JSON.stringify(p),callback:"JANRAIN.SSO.ENGAGE._loginCallback",bp_channel:a.bp_channel,logout_uri:a.logout_uri,segment:c})))};JANRAIN.SSO.check_login_dispatch=function(a,b){m||(m=new h(a.sso_server,"/static/server.html"));JANRAIN.SSO.log("checking for session");JANRAIN.SSO.debug_log("Segments to check: "+a.supported_segments_ary);m.getValue("","getAllVisited",
function(c,f){var p=v(a.xd_receiver),e=x(f.allVisited).some(function(a){if(p===v(a.xdReceiverURI))return a.isLoggedIn});a.supported_segments_ary.forEach(function(c){m.getValue(c,"get",function(f,p){b(a,p,c,e)})})})};JANRAIN.SSO._redirectCallback=function(a,b,c,f,p,g,l){(g=g||e)?!p&&!s?(JANRAIN.SSO.error("no session set, due to missing xd_receiver and logged_in_host parameters"),"function"===typeof l&&l()):(m||(m=new h(g,"/static/server.html")),JANRAIN.SSO.log("updating session"),m.getValue(p,"getSegment",
function(c,e){m.getValue(e.segment,"get",function(c,h){var m=[],n;if(h.visited){JANRAIN.SSO.log("visited: "+h.visited);m=x(h.visited);s||(s=C());var r=0;if(s)n=v(s);else for(var k=0;k<m.length;k++)q(m[k].xdReceiverURI).host==p&&r++;1<r&&(JANRAIN.SSO.log("multiple domains match, resetting visited"),m=[]);for(k=0;k<m.length;k++){var r=v(m[k].xdReceiverURI),u=q(m[k].xdReceiverURI);if("undefined"!==typeof r&&(r===n||u.host===p)){!0===m[k].isLoggedIn?JANRAIN.SSO.log("logging in again to: "+m[k].domain):
(JANRAIN.SSO.log("found and logging in to: "+m[k].domain),m[k].isLoggedIn=!0);m=[m[k]];break}}}else JANRAIN.SSO.warn("expected a visited list for segment "+e.segment+" - none found");JANRAIN.SSO._setSSOSession(a,b,JSON.stringify(m),f,g,e.segment,p,function(){"function"===typeof l&&l()})})})):(JANRAIN.SSO.error("no session set, due to missing sso server parameter"),"function"===typeof l&&l())};JANRAIN.SSO._setSSOSession=function(a,b,c,f,e,g,l,k){m||(m=new h(e,"/static/server.html"));JANRAIN.SSO.debug_log("visited expires:  "+
f);b={session_id:a,session_id_expires:b,visited:c,visited_expires:f,host:l};a?JANRAIN.SSO.log("setting session "+b.host+" with segment "+g):JANRAIN.SSO.log("updating the visited list for segment "+g);m.setValue(g,"set",b,function(a,b){"undefined"!==k&&"function"===typeof k&&k()})};JANRAIN.SSO._setSession=function(a,b,c,f,p,g){JANRAIN.SSO._setSSOSession(a,null,b,c,e,f,p,g)};JANRAIN.SSO.ENGAGE._login=function(a){if("undefined"===typeof e)JANRAIN.SSO.error("sso server is not defined");else{var b=document.createElement("script");
b.src=e+"/engage/loginx?v\x3d"+(new Date).getTime()+"\x26callback\x3d"+encodeURIComponent(a.callback)+"\x26xdcomm_uri\x3d"+encodeURIComponent(a.xd_receiver)+"\x26session_id\x3d"+encodeURIComponent(a.session_id)+"\x26visited\x3d"+encodeURIComponent(a.visited)+"\x26logout_uri\x3d"+encodeURIComponent(a.logout_uri)+"\x26bp_channel\x3d"+encodeURIComponent(a.bp_channel)+"\x26segment\x3d"+encodeURIComponent(a.segment);b.type="text/javascript";a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,
a)}};JANRAIN.SSO.ENGAGE._loginCallback=function(a){if(!a||"fail"===a.stat)JANRAIN.SSO.error("login failed: "+a.msg);else{JANRAIN.SSO.log("callback from SSO server received");m||(m=new h(e,"/static/server.html"));var b=q(window.location.hostname).host;JANRAIN.SSO.log("updating SSO session");b={session_id:decodeURIComponent(a.session_id),visited:decodeURIComponent(a.visited),visited_expires:a.visited_expires,host:b};JANRAIN.SSO.debug_log("ENGAGE._loginCallback: "+a.token);m.setValue(a.segment,"set",
b,function(b,f){JANRAIN.SSO.ENGAGE.post_token(a.token)})}};JANRAIN.SSO.ENGAGE.post_token=function(a){JANRAIN.SSO.log("posting token "+a+" to "+l);var b=n.document.createElement("form"),c=n.document.createElement("input");c.name="token";c.id="token";c.type="hidden";c.value=a;b.appendChild(c);b.method="POST";-1!=l.search(/\?/)?b.action=l+"\x26token\x3d"+a:b.action=l+"?token\x3d"+a;JANRAIN.SSO.log("form action: "+b.action);n.parent.document.getElementsByTagName("head")[0].appendChild(b);b.submit()};
JANRAIN.SSO.logout=function(a,b){E&&(callback_message="undefined"===typeof b?"callback function undefined":"callback: "+b.name,JANRAIN.SSO.debug_log("logout called "+callback_message+" caller name: '"+arguments.callee.caller.name+"'"));JANRAIN.SSO._deleteChecked();"undefined"!==typeof b&&"function"===typeof b&&(D=b);if("undefined"!==typeof a.sso_server){var c=q(window.location.hostname).host;if(window.localStorage&&!JANRAIN.SSO.useCookiesOnly())m||(m=new h(a.sso_server,"/static/server.html")),JANRAIN.SSO.log("removing session_id"),
m.getValue(c,"getSegment",function(f,e){m.getValue(e.segment,"getAllVisited",function(f,p){var g=[],h=[];if(p.allVisited){g=x(p.allVisited);h=JANRAIN.SSO._getLogoutUrls(g,s);JANRAIN.SSO.debug_log("SSO: logoutUrls: ",h);for(var l=[],k=0;k<g.length;k++){var n=q(g[k].xdReceiverURI).host;if(g[k].xdReceiverURI===s||n===c){g[k].isLoggedIn=!1;l=[g[k]];break}}g=l}toBeDeletedValue=p;toBeDeletedValue.session_id="deleteMe";toBeDeletedValue.visited=JSON.stringify(g);toBeDeletedValue.session_id_expires="deleteMe";
m.setValue(e.segment,"deleteSession",toBeDeletedValue,function(c,f){JANRAIN.SSO.log("session removed");JANRAIN.SSO._doLogout(a.logout_uri,h,b)})})});else{var f=n.document.createElement("script");f.setAttribute("src",a.sso_server+"/session/logout.js?logout_uri\x3d"+encodeURIComponent(a.logout_uri));document.getElementsByTagName("body")[0].appendChild(f)}}};JANRAIN.SSO._getLogoutUrls=function(a,b){var c=[],f;"undefined"!==typeof b&&(f=v(b));JANRAIN.SSO.debug_log("localSiteKey: "+f);for(var e=0;e<a.length;e++){var g=
v(a[e].xdReceiverURI),h=a[e].isLoggedIn;JANRAIN.SSO.debug_log(e+1+" this siteKey: "+g);h&&g!==f&&(JANRAIN.SSO.debug_log("logoutURI: "+a[e].logoutURI),c.push(a[e].logoutURI))}return c};JANRAIN.SSO._deleteChecked=function(){for(var a=n.document.cookie.split(";"),b=0;b<a.length;b++)-1<a[b].search(/janrain_sso_checked/)&&(n.document.cookie=a[b]+"\x3d;expires\x3d"+(new Date).toGMTString()+";path\x3d/;",JANRAIN.SSO.log("sso removed cookie "+a[b]))};JANRAIN.SSO.refresh=function(a){if("undefined"!==typeof a){var b=
n.document.createElement("script");b.setAttribute("src",a+"/session/refresh.js");document.getElementsByTagName("body")[0].appendChild(b)}};JANRAIN.SSO._doLogout=function(a,b,c){onComplete=function(){"undefined"!==typeof D&&"function"===typeof D?(JANRAIN.SSO.log("calling logout_callback()"),D()):"undefined"!==typeof a&&(JANRAIN.SSO.log("redirecting to "+a),n.document.location.href=a)};JANRAIN.SSO._loadUrls(b,onComplete)};JANRAIN.SSO._loadUrls=function(a,b){onComplete=function(){"undefined"!==typeof b&&
"function"===typeof b&&b()};if(null!=a&&0<a.length){var c=0;onFrameLoad=function(){++c;c>=a.length&&onComplete()};for(var f,e=0;e<a.length;e++)n.document.all?(f=document.createElement("div"),f.innerHTML='\x3ciframe onload\x3d"onFrameLoad();"\x3e\x3c/iframe\x3e',f=f.firstChild):(f=n.document.createElement("iframe"),f.onload=onFrameLoad),f.setAttribute("src",decodeURIComponent(a[e])),JANRAIN.SSO.log("calling logout url "+e+" of "+a.length+": "+a[e]),n.document.getElementsByTagName("head")[0].appendChild(f)}else onComplete()};
q.options={strictMode:!1,key:"source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};
Array.prototype.forEach=Array.prototype.forEach||function(a,b){var c=this.length>>>0;if("function"!=typeof a)throw new TypeError;for(var f=0;f<c;f++)f in this&&a.call(b,this[f],f,this)};Array.prototype.some||(Array.prototype.some=function(a,b){if(null==this)throw new TypeError;var c,f=Object(this),e=f.length>>>0;if("function"!==typeof a)throw new TypeError;for(c=0;c<e;c++)if(c in f&&a.call(b,f[c],c,f))return!0;return!1});_array_contains=function(a,b){if("undefined"===typeof a||null===a)return!1;for(var c=
a.length;c--;)if(a[c]===b)return!0;return!1};h.prototype={constructor:h,init:function(){var a=this;if(!this._iframe)if(window.postMessage&&window.JSON&&window.localStorage&&!JANRAIN.SSO.useCookiesOnly()){this._iframe=document.createElement("iframe");this._iframe.style.cssText="position:absolute;width:1px;height:1px;left:-9999px;";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(this._iframe,b);window.addEventListener?(this._iframe.addEventListener("load",function(){a._iframeLoaded()},
!1),window.addEventListener("message",function(b){a._handleMessage(b)},!1)):this._iframe.attachEvent&&(this._iframe.attachEvent("onload",function(){a._iframeLoaded()},!1),window.attachEvent("onmessage",function(b){a._handleMessage(b)}))}else throw Error("Unsupported browser.");this._iframe.src=this.origin+this.path},getValue:function(a,b,c){a={request:{key:a,messageId:++this._messageId,action:b},callback:c};this._iframeReady?this._sendRequest(a):this._queue.push(a);this._iframe||this.init()},setValue:function(a,
b,c,e){a={request:{key:a,messageId:++this._messageId,action:b,storedValue:c},callback:e};this._iframeReady?this._sendRequest(a):this._queue.push(a);this._iframe||this.init()},removeValue:function(a,b){var c={request:{key:a,messageId:++this._messageId,action:"remove"},callback:b};this._iframeReady?this._sendRequest(c):this._queue.push(c);this._iframe||this.init()},_sendRequest:function(a){this._requests[a.request.messageId]=a;this._iframe.contentWindow.postMessage(JSON.stringify(a.request),this.origin)},
_iframeLoaded:function(){this._iframeReady=!0;if(this._queue.length){for(var a=0,b=this._queue.length;a<b;a++)this._sendRequest(this._queue[a]);this._queue=[]}},_handleMessage:function(a){if(a.origin==this.origin){var b;try{b=JSON.parse(a.data)}catch(c){JANRAIN.SSO.warn("json object did not parse: "+array),b={}}"undefined"!==typeof b.messageId&&(this._requests[b.messageId].callback(b.key,b.storedValue),delete this._requests[b.messageId])}}}}})(this);var JSON;JSON||(JSON={});
(function(){function n(h){return 10>h?"0"+h:h}function x(h){C.lastIndex=0;return C.test(h)?'"'+h.replace(C,function(h){var l=v[h];return"string"===typeof l?l:"\\u"+("0000"+h.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+h+'"'}function A(h,n){var l,e,r,s,u=t,k,g=n[h];g&&"object"===typeof g&&"function"===typeof g.toJSON&&(g=g.toJSON(h));"function"===typeof q&&(g=q.call(n,h,g));switch(typeof g){case "string":return x(g);case "number":return isFinite(g)?""+g:"null";case "boolean":case "null":return""+
g;case "object":if(!g)return"null";t+=z;k=[];if("[object Array]"===Object.prototype.toString.apply(g)){s=g.length;for(l=0;l<s;l+=1)k[l]=A(l,g)||"null";r=0===k.length?"[]":t?"[\n"+t+k.join(",\n"+t)+"\n"+u+"]":"["+k.join(",")+"]";t=u;return r}if(q&&"object"===typeof q){s=q.length;for(l=0;l<s;l+=1)"string"===typeof q[l]&&(e=q[l],(r=A(e,g))&&k.push(x(e)+(t?": ":":")+r))}else for(e in g)Object.prototype.hasOwnProperty.call(g,e)&&(r=A(e,g))&&k.push(x(e)+(t?": ":":")+r);r=0===k.length?"{}":t?"{\n"+t+k.join(",\n"+
t)+"\n"+u+"}":"{"+k.join(",")+"}";t=u;return r}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+n(this.getUTCMonth()+1)+"-"+n(this.getUTCDate())+"T"+n(this.getUTCHours())+":"+n(this.getUTCMinutes())+":"+n(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var B=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
C=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,t,z,v={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},q;"function"!==typeof JSON.stringify&&(JSON.stringify=function(h,n,l){var e;z=t="";if("number"===typeof l)for(e=0;e<l;e+=1)z+=" ";else"string"===typeof l&&(z=l);if((q=n)&&"function"!==typeof n&&("object"!==typeof n||"number"!==typeof n.length))throw Error("JSON.stringify");return A("",{"":h})});
"function"!==typeof JSON.parse&&(JSON.parse=function(h,n){function l(e,h){var q,k,g=e[h];if(g&&"object"===typeof g)for(q in g)Object.prototype.hasOwnProperty.call(g,q)&&(k=l(g,q),void 0!==k?g[q]=k:delete g[q]);return n.call(e,h,g)}var e;h=""+h;B.lastIndex=0;B.test(h)&&(h=h.replace(B,function(e){return"\\u"+("0000"+e.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(h.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+h+")"),"function"===typeof n?l({"":e},""):e;throw new SyntaxError("JSON.parse");})})();

}
/*
     FILE ARCHIVED ON 12:08:00 Feb 08, 2014 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 12:09:17 Dec 14, 2024.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 0.455
  exclusion.robots: 0.018
  exclusion.robots.policy: 0.008
  esindex: 0.008
  cdx.remote: 20.925
  LoadShardBlock: 377.794 (3)
  PetaboxLoader3.datanode: 212.113 (5)
  PetaboxLoader3.resolve: 407.395 (3)
  load_resource: 426.526 (2)
*/